### ISSUE TITLE
missing ids in tuya module mappings.py

### ISSUE THREAD

**Issue by MarcProe** [fhempy/fhempy#101]
Hi,

I have two tuya devices that are not in mappings.py, and therefore cannot be controlled locally.

- Nous A1 WiFi+BT
- A60-PA-WIFILIC-TY-CCT

Is there a possibility to get the data needed for mappings.py and integrate the devices?
I will gladly do it, if I know how to. I have access to a tuya IoT Platform account.

Thanks!

**Comment by fhempy** [comment]
Hi,

you can use the module with API KEY and API SECRET. It retrieves the mappings from the cloud but still does everything else locally.

**Comment by MarcProe** [comment]
When I use API KEY and API SECRET the tuya_spec_functions and tuya_spec_status fields are populated, but the device stays in status "Initializing...".

Can I derive the mappings.py entry from the attribute values?

**Comment by fhempy** [comment]
Ah, I think it's a version 3.4 device which is not supported yet.

**Comment by MarcProe** [comment]
Yes, it is. That explains the problems, thanks! I will use ioBroker in the meantime.
