### ISSUE TITLE
Update controls

### ISSUE THREAD

**Issue by fhempy** [fhempy/fhempy#105]
@sidey79 ich glaube das Update Controls funktioniert noch nicht. Habe hier einen Fehler:
https://github.com/fhempy/fhempy/actions/runs/3450915394/jobs/5759807996

Kannst du dir das bitte anschauen? Danke dir für die Actions, das ist wirklich sehr hilfreich!

**Comment by sidey79** [comment]
Wir sollten das mal beobachten.

In diesem Fall hat der Job aus deinem Repo versucht was in meinem Fork zu aktualisieren.
Das geht leider nicht, weil die Rechte fehlen.

Wenn das noch mal vorkommen sollte, könnte eine Prüfung eingebaut werden, ob Zielbranche in einem anderen Account liegt.

**Comment by fhempy** [comment]
Kann es sein, dass man den update_controls Teil vom Test Teil im Workflow trennen muss und 2 yamls definieren? Weil aktuell werden jedes mal die Controls aktualisiert, obwohl ich die Perl Dateien nicht angreife.

**Comment by sidey79** [comment]
Wenn im master ein push gemacht wird, dann wird das control file immer versucht zu aktualisieren (sofern es wirklich was zu aktualisieren gibt).
Ebenso wird der Test dann ausgeführt.

Ich rate jetzt mal, dass immer ein commit stattfindet, und die Dateien immer den Zeitstempel vom letzten commit erhalten. Wenn das so ist, dann müsste man einfach mehr als nur den letzten commit auschecken und hätte auch keine Veränderungen.

**Comment by fhempy** [comment]
Hmm...es wird aber auch aktualisiert, wenn keine Änderungen gemacht worden sind.
Siehe hier z.B.
https://github.com/fhempy/fhempy/commits/master

Für die v0.1.522 hat sich an den .pm Files nichts geändert, es wurde aber dennoch das Control File mit den aktuellen Datum versehen. Ist nicht dramatisch schlimm, nur werden dann bei jedem FHEM Update die Files aktualisiert obwohl sich nichts geändert hat.

**Comment by sidey79** [comment]
Jepp, wie vermutet.

Push im master branch und dann greift das standard git Verhalten, dass nur der letzte commit ausgecheckt ist. Alle Dateien haben dann den Zeitstempel vom letzten commit und das führt dann dazu, dass im controls_file eine Änderung vermerkt ist.

Man könnte einfach alle commits laden, dann wäre würde der Zeitstempel entscheiden.

**Comment by fhempy** [comment]
Ich mach das hier zu, da es nun super funktioniert :)

Als nächstes muss ich noch semantic-release als Github Action abbilden, dann kann ich das release.sh Script los werden.
