### ISSUE TITLE
state Initializing...

### ISSUE THREAD

**Issue by markusmainz** [fhempy/fhempy#106]
Hello,
since a few weeks after updateing fhempy my Heatpump dont work
as local tuya device.
state Initializing... all the time
Im on the 0.1.520 now

**Comment by fhempy** [comment]
Hi,
thx for reporting!

What about the commands? Do commands show up in the FHEM web?

**Comment by jfmennedy** [comment]
Hi, same problem for my local tuya devices since a while. After a restart of fhempy I can send commands to my tuya devices and after a certain time there is just an exception...

2022-11-20 09:29:24,188 - ERROR    - fhempy.lib.fhem_pythonbinding: Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 367, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 438, in execute_function
    ret = await asyncio.wait_for(
  File "/usr/lib/python3.9/asyncio/tasks.py", line 481, in wait_for
    return fut.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 186, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 289, in handle_set
    return await fct_call(hash, final_params)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 249, in set_boolean
    await self._connected_device.set_dp(onoff, switch_id)
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/pytuya/__init__.py", line 521, in set_dp
    return await self.exchange(SET, {str(dp_index): value})
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/pytuya/__init__.py", line 462, in exchange
    self.transport.write(payload)
AttributeError: 'NoneType' object has no attribute 'write'
 with hash: {'argsh': {}, 'function': 'Set', 'id': 8069771, 'defargs': ['kuKonvektor', 'fhempy', 'tuya', 'utzgmksz7zj66als', '54370018a4e57c9dc4c2', '192.168.0.183', '29dc0a9bd724f46a'], 'FHEMPYTYPE': 'tuya', 'args': ['kuKonvektor', 'Power', 'on'], 'msgtype': 'function', 'defargsh': {}, 'PYTHONTYPE': 'tuya', 'NAME': 'kuKonvektor'}

**Comment by fhempy** [comment]
Can you please check with version 0.1.521. It checks every 60s if the connection dropped. It's not perfect, but should hopefully be a workaround.
I need to implement version 3.4 support which requires me to refactor the code which should hopefully be a more complete fix.

**Comment by jfmennedy** [comment]
I updated to 521 and will give you feedback the next days.. I don't know when the connection drops.. As I said after reboot it works fine but after a while it won't work anymore..

I never made updates on my tuya devices.. They always worked.. Do you think that might be related to newer api version?

**Comment by fhempy** [comment]
I think they must have changed something on the devices. I have the same issue, that after some days the connection gets lost. The tuya code in fhempy which is relevant for the connection wasn't changed the last months:
https://github.com/fhempy/fhempy/commits/master/FHEM/bindings/python/fhempy/lib/tuya/pytuya

**Comment by markusmainz** [comment]
Same Initializing State on my Installation with 0.1.522 .
How can i downgrade the fhempy to check if it worked with an older Version.
I saw that the last succesfull read was on
2022-10-11 12:06:42

**Comment by fhempy** [comment]
```
sudo -u fhem bash
pip3 install fhempy==0.1.504
```
After that restart fhempy. Let me know if it works with that version. Thx!

**Comment by jfmennedy** [comment]
A short feedback from my side.. Yesterday evening and this morning the devices were still in function but this evening they don't work anymore... Exception is the same as posted before...

**Comment by fhempy** [comment]
@jfmennedy can you please test with version 0.1.504 if it also disconnects?

@markusmainz does it work for you with version 0.1.504?

**Comment by jfmennedy** [comment]
can just check it monday, i am on the road this weekend...

**Comment by jfmennedy** [comment]
just downgraded my testing-peer to 504. will monitor the next day...

**Comment by jfmennedy** [comment]
Tested 504 for some days and no disconnects...

**Comment by fhempy** [comment]
Thanks for testing! That helps a lot to find the root cause.

I'll let you know as soon as I have something ready to test.

**Comment by fhempy** [comment]
Can you please test with the latest release 0.1.528. That one should hopefully this bug.

**Comment by klauswitt** [comment]
Downgrade to version 504 did not work for my. But 528 brought a progress.
My RGB+CCT bulb is working now locally.
Brightness, colour temperature, work mode (white, colour, etc.) is working now.
Set on/off is not existing. Instead of this "set switch_led on|off" can be used.
But colour_data_v2 is existing as set option, but not as reading. And it is not possible to change the colour.

**Comment by fhempy** [comment]
Please open another issue for the colour_data_v2 problem (including current readings and attribute states) so that I can handle that separately.  Thanks!

**Comment by pseudex** [comment]
**Version:**
fhempy_local | 0.1.535

My sockes (gosund SP112_RTL) won't initialize either.

I did a test with python directly and the device is answering
```python
#!/usr/bin/env python3

import tinytuya
a = tinytuya.OutletDevice('DEVICE_ID', '192.168.IP.IP', 'LOCAL_ID')
a.set_version(3.3)
data = a.status()

print(data)
```

python3 tuyatest.py 
```
{'dps': {'1': True, '7': True, '9': 0, '15': 0, '18': 0, '19': 0, '20': 2340, '21': 1, '22': 568, '23': 30696, '24': 16292, '25': 1280, '38': '2', '39': 'relay', '40': False, '41': '', '42': '', '43': '', '101': False}}
```
first I thought it will not work because the IOT service trial in tuya is expired.

it there anything else I can to do to do the debugging?

**Comment by pseudex** [comment]
I found the Problem why my fhempy was not working anymore.
There was the wrong version of tinytuya installed. It was the one from Jason from PyPi.
Manually installed the version listed here in the manifest

Colorama I had to install manually before the setup of tinytuya was working

"git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3"

<pre><font color="#26A269"><b>user@server</b></font>:<font color="#12488B"><b>/opt/fhem</b></font>$ sudo -u fhem python3 -m pip uninstall tinytuya
Found existing installation: tinytuya 1.4.0
Uninstalling tinytuya-1.4.0:
  Would remove:
    /opt/fhem/.local/lib/python3.9/site-packages/sandbox/*
    /opt/fhem/.local/lib/python3.9/site-packages/tinytuya-1.4.0.dist-info/*
    /opt/fhem/.local/lib/python3.9/site-packages/tinytuya/*
Proceed (y/n)? y
  Successfully uninstalled tinytuya-1.4.0
</pre>
<pre><font color="#26A269"><b>user@server</b></font>:<font color="#12488B"><b>/opt/fhem</b></font>$ sudo -u fhem python3 -m pip install &quot;git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3&quot;
Collecting git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3
  Cloning https://github.com/fhempy/tinytuya to /tmp/pip-req-build-lpr65b5_
  Running command git clone -q https://github.com/fhempy/tinytuya /tmp/pip-req-build-lpr65b5_
<font color="#C01C28">    ERROR: Command errored out with exit status 1:</font>
<font color="#C01C28">     command: /usr/bin/python3 -c &apos;import sys, setuptools, tokenize; sys.argv[0] = &apos;&quot;&apos;&quot;&apos;/tmp/pip-req-build-lpr65b5_/setup.py&apos;&quot;&apos;&quot;&apos;; __file__=&apos;&quot;&apos;&quot;&apos;/tmp/pip-req-build-lpr65b5_/setup.py&apos;&quot;&apos;&quot;&apos;;f=getattr(tokenize, &apos;&quot;&apos;&quot;&apos;open&apos;&quot;&apos;&quot;&apos;, open)(__file__);code=f.read().replace(&apos;&quot;&apos;&quot;&apos;\r\n&apos;&quot;&apos;&quot;&apos;, &apos;&quot;&apos;&quot;&apos;\n&apos;&quot;&apos;&quot;&apos;);f.close();exec(compile(code, __file__, &apos;&quot;&apos;&quot;&apos;exec&apos;&quot;&apos;&quot;&apos;))&apos; egg_info --egg-base /tmp/pip-pip-egg-info-9ht3i4ze</font>
<font color="#C01C28">         cwd: /tmp/pip-req-build-lpr65b5_/</font>
<font color="#C01C28">    Complete output (9 lines):</font>
<font color="#C01C28">    Traceback (most recent call last):</font>
<font color="#C01C28">      File &quot;&lt;string&gt;&quot;, line 1, in &lt;module&gt;</font>
<font color="#C01C28">      File &quot;/tmp/pip-req-build-lpr65b5_/setup.py&quot;, line 3, in &lt;module&gt;</font>
<font color="#C01C28">        from tinytuya import __version__</font>
<font color="#C01C28">      File &quot;/tmp/pip-req-build-lpr65b5_/tinytuya/__init__.py&quot;, line 92, in &lt;module&gt;</font>
<font color="#C01C28">        from .core import *</font>
<font color="#C01C28">      File &quot;/tmp/pip-req-build-lpr65b5_/tinytuya/core.py&quot;, line 67, in &lt;module&gt;</font>
<font color="#C01C28">        from colorama import init</font>
<font color="#C01C28">    ModuleNotFoundError: No module named &apos;colorama&apos;</font>
<font color="#C01C28">    ----------------------------------------</font>
<font color="#A2734C">WARNING: Discarding git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.</font>
<font color="#C01C28">ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.</font>
<font color="#26A269"><b>user@server</b></font>:<font color="#12488B"><b>/opt/fhem</b></font>$ sudo -u fhem python3 -m pip install coloram
^C<font color="#C01C28">ERROR: Operation cancelled by user</font>
<font color="#26A269"><b>user@server</b></font>:<font color="#12488B"><b>/opt/fhem</b></font>$ sudo -u fhem python3 -m pip install colorama
Collecting colorama
  Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: colorama
Successfully installed colorama-0.4.6
<font color="#26A269"><b>user@server</b></font>:<font color="#12488B"><b>/opt/fhem</b></font>$ sudo -u fhem python3 -m pip install &quot;git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3&quot;
Collecting git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3
  Cloning https://github.com/fhempy/tinytuya to /tmp/pip-req-build-tn4achd5
  Running command git clone -q https://github.com/fhempy/tinytuya /tmp/pip-req-build-tn4achd5
Requirement already satisfied: colorama in ./.local/lib/python3.9/site-packages (from tinytuya==1.7.3) (0.4.6)
Requirement already satisfied: pycryptodome in ./.local/lib/python3.9/site-packages (from tinytuya==1.7.3) (3.15.0)
Requirement already satisfied: requests in ./.local/lib/python3.9/site-packages (from tinytuya==1.7.3) (2.26.0)
Requirement already satisfied: charset-normalizer~=2.0.0 in ./.local/lib/python3.9/site-packages (from requests-&gt;tinytuya==1.7.3) (2.0.12)
Requirement already satisfied: idna&lt;4,&gt;=2.5 in /usr/lib/python3/dist-packages (from requests-&gt;tinytuya==1.7.3) (2.10)
Requirement already satisfied: urllib3&lt;1.27,&gt;=1.21.1 in /usr/lib/python3/dist-packages (from requests-&gt;tinytuya==1.7.3) (1.26.5)
Requirement already satisfied: certifi&gt;=2017.4.17 in /usr/lib/python3/dist-packages (from requests-&gt;tinytuya==1.7.3) (2020.6.20)
Building wheels for collected packages: tinytuya
  Building wheel for tinytuya (setup.py) ... done
  Created wheel for tinytuya: filename=tinytuya-1.7.3-py3-none-any.whl size=80904 sha256=1b619cb0fce1c8a60eece3a7b6ebc5166557a8074223627665bdb4a0117f1c55
  Stored in directory: /tmp/pip-ephem-wheel-cache-knah6qww/wheels/13/7b/72/e7695511186ed22b99669f240c56aead6bfc70bb6592d7e157
Successfully built tinytuya
Installing collected packages: tinytuya
Successfully installed tinytuya-1.7.3
</pre>

**Comment by fhempy** [comment]
After a restart of fhempy the proper tinytuya version should be installed automatically. Unfortunately tinytuya doesn't support async, therefore I had to fork a copy to my own repository.

I'm going to close that one, please open another issue if you still notice any issues.
