### ISSUE TITLE
tuya_cloud_connector login fehler: request time is invalid

### ISSUE THREAD

**Issue by klauswitt** [fhempy/fhempy#112]
Erst mal noch nen gesundes Neues!

parallel habe ich zum testen auch tuya_cloud im Einsatz. Die hatte in der Version 0.1.526 gut funktioniert.
Jetzt nach dem update aud 0.1.538 bleibt der connector offline und ich bekomme folgenden fehler:

2023-01-03 12:14:41,656 - ERROR    - tuya_cloud_connector: Tuya login error response: {'code': 1013, 'msg': 'request time is invalid', 'success': False, 't': 1672746629471, 'tid': 'd1fcff608b5c11ed9155f6a8c25a9394'}

**Comment by fhempy** [comment]
Wünsche dir auch alles Gute im neuen Jahr!

Hier habe ich was bei den HA Kollegen gefunden:
https://community.home-assistant.io/t/tuya-integration-problem-login-error-1013-request-time-is-invalid/386231

Ist die Uhrzeit falsch eingestellt?

**Comment by klauswitt** [comment]
Es lag wirklich an der Uhrzeit, die lag 20min daneben. 
Der ntp war nicht vorhanden. Seltsam das die Zeit überhaupt einigermaßen stimmte. 
Nach Installation des ntp ist der tuya_cloud_connector online.

Die Devices sollten doch automatisch angelegt werden (ich habe beim probieren etwas den Überblick verloren)? Bei der Version 0.1.528 hatte ich meine 2 Lampen gesehen.
Jetzt wird keine angelegt.

**Comment by fhempy** [comment]
Genau, die Devices werden automatisch angelegt. Gibt es die Devices vielleicht schon mit gleichen Namen als local Device?

**Comment by klauswitt** [comment]
Nein, es gibt keine tuya Decices auf dem System. Nach dem löschen sind sie nicht wieder aufgetaucht. Ich probiere das Ganze auf meinem Testsystem aus. Da gibt es nicht viele defines:

list .*


APT
FileLog_MQTT2_f16
Logfile
MQTT2_ebusd
MQTT2_f16
Signalbot
WEB
WEB_127.0.0.1_38910
WEB_127.0.0.1_38920
WEB_127.0.0.1_44322
WEB_127.0.0.1_44334
WEB_127.0.0.1_47438
WEB_127.0.0.1_47448
WEB_127.0.0.1_47452
WEB_127.0.0.1_47462
WEB_127.0.0.1_47492
WEB_127.0.0.1_51034
WaveshareRS485
autocreate
c_dello
eventTypes
fhemInstaller
fhempy_local
fhempyserver_15733
global
initialUsbCheck
mqtt2
msgconfig
nf.Signalbot
npm
tuya_cloud_connector
tuya_system
widgets

**Comment by klauswitt** [comment]
Ich meinte eigentlich, das ich es dort momentan laufen habe :)
Aber ich habe jetzt nochmal alle fhempy module in fhem gelöscht, neu gestartet und wieder angelegt.

define fhempy_local BindingsIo fhempy
define tuya_cloud_connector fhempy tuya_cloud setup j...g 8...c k...k@gmail.com d...R

Danach beide Leuchten vom Netz getrennnt und wieder angesteckt, paar mal mit der App geschaltet.
Es werden keine neuen Devices angelegt.
Die Lampen sind als Devices in dem Cloud Project vorhanden, zu dem KEY und SECRET passen.

**Comment by fhempy** [comment]
Ich denke wir haben hier den gleichen Fehler wie hier: https://github.com/fhempy/fhempy/issues/109

Ich schließe das Issue mal und sollte nach dem beheben von https://github.com/fhempy/fhempy/issues/109 hier noch ein Fehler auftreten, dann gerne öffnen.
