### ISSUE TITLE
ERROR: empty name in readingsBeginUpdate

### ISSUE THREAD

**Issue by RockFan89** [fhempy/fhempy#113]
Hallo und gutes neues Jahr!

Gestern ist mein FHEM-Log mit folgender Fehlermeldung vollgelaufen:
2023.01.04 11:10:34 1: ERROR: empty name in readingsBeginUpdate
2023.01.04 11:10:34 1: stacktrace:
2023.01.04 11:10:34 1:     main::readingsBeginUpdate           called by (eval 268166) (1)
2023.01.04 11:10:34 1:     (eval)                              called by ./FHEM/10_BindingsIo.pm (561)
2023.01.04 11:10:34 1:     main::BindingsIo_processMessage     called by ./FHEM/10_BindingsIo.pm (676)
2023.01.04 11:10:34 1:     main::BindingsIo_readWebsocketMessage called by ./FHEM/10_BindingsIo.pm (296)
2023.01.04 11:10:34 1:     main::BindingsIo_Read               called by fhem.pl (3976)
2023.01.04 11:10:34 1:     main::CallFn                        called by fhem.pl (784)
Use of uninitialized value $d in hash element at fhem.pl line 4691.
Use of uninitialized value $name in concatenation (.) or string at fhem.pl line 5030.
2023.01.04 11:10:34 1: readingsUpdate(,state,offline) missed to call readingsBeginUpdate first.
2023.01.04 11:10:34 1: stacktrace:
2023.01.04 11:10:34 1:     main::readingsBulkUpdate            called by fhem.pl (5012)
2023.01.04 11:10:34 1:     main::readingsBulkUpdateIfChanged   called by (eval 268166) (1)
2023.01.04 11:10:34 1:     (eval)                              called by ./FHEM/10_BindingsIo.pm (561)
2023.01.04 11:10:34 1:     main::BindingsIo_processMessage     called by ./FHEM/10_BindingsIo.pm (676)
2023.01.04 11:10:34 1:     main::BindingsIo_readWebsocketMessage called by ./FHEM/10_BindingsIo.pm (296)
2023.01.04 11:10:34 1:     main::BindingsIo_Read               called by fhem.pl (3976)
2023.01.04 11:10:34 1:     main::CallFn                        called by fhem.pl (784)
Use of uninitialized value $d in hash element at fhem.pl line 4766.
Use of uninitialized value $dev in hash element at fhem.pl line 3839.

Der Block wiederholt sich innerhalb von ein paar Sekunden 3-mal.

Leider finde ich keinen direkten Auslöser. Gestern kam es durchgehend, wodurch das Log mal eben auf 250MB angewachsen ist, bis ich den fhempy-Server gestoppt habe.

Ich habe dann FHEM und auch fhempy auf die aktuelle Version aktualisiert. Heute kommt der dreifach wiederholende Gesamtfehlerblock alle 5 Minuten.

Ich habe mal alle noch vorhandenen Logs durchforstet und festgestellt, dass es immer wieder einmal Tage mit diesen Einträgen gibt. Dann liegen wieder viele Monate bis zum nächsten Vorkommen dazwischen.  Solange es nur ein paar Einträge sind sehe ich kein Problem. Wenn es allerdings, so wie gestern, den Speicher komplett voll schreibt, schon.

Irgend eine Idee?

Viele Grüße
Dieter

**Comment by fhempy** [comment]
Hi,
welche Devices hast du alles im Einsatz? Du kannst mir die Devices aus dem FHEM Log beim rauskopieren, da steht immer ```
2023.01.01 18:34:59 3: fhempy v1.0.0 (gree_climate)
2023.01.01 18:34:59 3: fhempy v1.0.0 (tuya)
```

Ist es möglich, dass du ein Device gelöscht hast und es dadurch passiert ist?

**Comment by RockFan89** [comment]
Hi Dominik,

Folgende Devices sind bei mir definiert (für manche, wie z.B. Rauchmelder, Temperatursensoren, etc. natürlich mehrere):
fhempy v1.0.0 (bt_presence)            
fhempy v1.0.0 (dlna_dmr)               
fhempy v1.0.0 (discover_upnp)          
fhempy v1.0.0 (xiaomi_tokens)          
fhempy v1.0.0 (miio)                   
fhempy v1.0.0 (googlecast)             
fhempy v1.0.0 (xiaomi_gateway3)        
fhempy v1.0.0 (xiaomi_gateway3_device) 
fhempy v1.0.0 (miscale)                
fhempy v1.0.0 (google_weather)         

Außerdem arbeite ich mit 2 Peers.

Bzgl. Löschen:
Gelöscht habe ich nicht ABER möglicherweise könnte es zeitlich einen Zusammenhang zu neuen Devices geben, die ich dann in verständliche Namen umbenannt habe. Ich kann mich auch erinnern, dass du im Forum geschrieben hast, dass fhempy das nicht automatisch handeln kann. Deshalb habe ich auch den fhempyServer neu gestartet. Selbst nach einem Neustart von FHEM kamen sie noch. Seit einem weiteren Neustart heute Abend scheinen sie aber verschwunden zu sein (soweit ich das jetzt schon sagen kann).

Viele Grüße
Dieter

**Comment by fhempy** [comment]
Am Rename kann es auch liegen. Weißt du vielleicht noch welches Device du renamed hast?

**Comment by RockFan89** [comment]
Ja, es war ein Rauchmelder:

PYTHONTYPE | xiaomi_gateway3_device

**Comment by fhempy** [comment]
Ich habe gerade ein Update bereitgestellt. Nun sollte das Rename richtig funktionieren.
Bitte mal mit 0.1.541 testen - ist in paar Minuten online. Danke!

**Comment by RockFan89** [comment]
Habe mehrmals Rename gemacht seit gestern Abend und keine Einträge mehr mit "ERROR: empty name in readingsBeginUpdate" im Log.
Sieht also gut aus.
Vielen Dank für die Korrektur!!

**Comment by fhempy** [comment]
Perfekt, danke dass du den Bug gefunden und gemeldet hast! 👍
