### ISSUE TITLE
bluepy-helper uses almost 100% CPU with eq3bt module

### ISSUE THREAD

**Issue by mayonezo** [fhempy/fhempy#117]
The process bluepy-helper uses almost 100% CPU after a while. Restarting fhem resolves the issue temporarily until bluepy-helper unreasonably increases CPU usage again.

I solely use the eq3bt module with fhempy, which works somewhat reliably after every fhem restart. I use this bluetooth dongle [https://www.feasycom.net/beacon/bluetooth--adapter/long-range-bluetooth-usb-dongle-adapter.html](https://www.feasycom.net/beacon/bluetooth--adapter/long-range-bluetooth-usb-dongle-adapter.html) on my Raspberry Pi 3B+ with 64bit Raspbian. I tried turning off the integrated bluetooth module via the config.txt file, but it did not resolve the issue.

fhempy & fhem were updated today and the issue still persists.

**Comment by fhempy** [comment]
Do you have the same issues with the internal Bluetooth hardware module? Bluepy isn't well maintained right now and I read that it doesn't support Python 3.10 either. So it might be that I need to switch to another Bluetooth library anyway, but please don't expect that this will be done in the next few weeks.

**Comment by mayonezo** [comment]
Yes, the same thing happened with the internal Bluetooth hardware module.

**Comment by fhempy** [comment]
Did it work in the past? Could be that 64bit isn't supported well by bluepy.

**Comment by mayonezo** [comment]
No, it was never really stable. I just recently found out about bluepy-helper hogging the CPU.

**Comment by mayonezo** [comment]
Oh, and yes: I use a 64bit OS for the Raspi.

**Comment by fhempy** [comment]
I just migrated blue_connect from bluepy to bleak for testing purposes. I'll monitor the connection during the next few days and if it works stable, I would migrate eq3bt as well.

**Comment by mayonezo** [comment]
That would be awesome! Now that I know what is causing the hangs, I reset fhem almost every other hour. So another Bluetooth library would be really appreciated!

**Comment by fhempy** [comment]
Bleak bluetoothle code is prepared and working pretty well.

I think that I can create a first test version of eq3bt with bleak next week.

**Comment by fhempy** [comment]
Please do a test with the latest fhempy version. Make sure that your raspi is up2date before the update!

**Comment by mayonezo** [comment]
This is what I did:
Raspi: sudo apt update && sudo apt dist-upgrade
fhem: update and then shutdown restart

Sadly, it does not work. All my thermostats are stuck with the reading: connection connecting

My fhempy log does not show up in fhem, but I can copy it from /opt/fhem/log. See it attached here:

[fhempy-2023-01-16.log](https://github.com/fhempy/fhempy/files/10429860/fhempy-2023-01-16.log)

**Comment by fhempy** [comment]
Please the again with the latest version.

**Comment by mayonezo** [comment]
It seems that I can now set the thermostats but I don't get any values yet. Reading connection is now "connected" but I get completeState "unknown". 

fhempy log still does not show up in fhem web.

Today's log is attached.
[fhempy-2023-01-18.log](https://github.com/fhempy/fhempy/files/10447906/fhempy-2023-01-18.log)

**Comment by fhempy** [comment]
Please try the procedure described here
https://github.com/rytilahti/python-eq3bt#pairing

Even if you don't have firmware 120+ it requires to be paired once. Afterwards restart Bluetooth by sudo systemctl restart bluetooth

**Comment by mayonezo** [comment]
I gave it a try. All of them were already paired before in that way, since I have two thermostats that are on the newer firmware 146 and two with firmware 120, so I did not expect much to happen. But apparently I had to re-pair them (pun kind of intended).

I will test stability in the next few weeks.

Thank you so much for switching bluetooth libraries in such a short time!

**Comment by fhempy** [comment]
I had to re-pair the thermostats as well - don't know why...

The cool thing about bleak library is, that disconnects can be detected and re-connection process can be initiated immediately. My connection is stable for 3 days already.

Now we have a well maintained bluetooth library in fhempy 👍 

I'm going to close the issue. Please open a new one if you have issues with the new version.
