### ISSUE TITLE
[feature-request] fhempy - Tuya: add disable attribute

### ISSUE THREAD

**Issue by pseudex** [fhempy/fhempy#118]
Hi,

most devices have the disable attribute. fhempy tuya devices don't have this attribute.
This would be handy with devices which are registered in fhem but not connected to power.

this is an example from tplink hs110 module.
```
disable
Disables the corresponding device. Note: it can be toggled by issuing the following command:

attr <device> disable toggle
```

**Comment by jfmennedy** [comment]
I would appreciate that feature also to disable temporarily not available devices

**Comment by fhempy** [comment]
I was thinking already about a generic disable attribute for all fhempy devices. Actually I just need to call Undefine if 1 and Define if 0 or deleted.

Can you please explain why you would like to disable offline tuya devices? Actually they should be recognized as offline and automatically switch to online as soon as they are online again. Therefore I can't get the use case right now.

**Comment by jfmennedy** [comment]
In my case I use some heating devices which are turned off in summer period or some googlecast devices which are connected to tv´s and not reachable when the tv is turnend off. I would like to disable them when the devices are not reachable. I use a structure of all fhempy devices and the state of this structure is used for maintenance and surveillance reasons...

**Comment by fhempy** [comment]
I was just thinking about the implementation of the generic disable attribute.

Actually it should be straight forward:
 - disable 1 => Call fhempy module Undefine
 - disable 0  or attr deleted => Call fhempy module Define

The question is what happens on startup when define is loaded already from fhem.cfg but disable attr is called afterwards. I think it's impossible to prevent loading the fhempy device for a short time until disable is handled from fhem.cfg by fhem and sent over to fhempy.

I checked the DOIF module how it is handled there, but it's the same:
https://github.com/mhop/fhem-mirror/blob/master/fhem/FHEM/98_DOIF.pm#L3729
it can't be guaranteed that the attribute is already available at that line of code.

Any thoughts?

**Comment by jfmennedy** [comment]
_it's impossible to prevent loading the fhempy device for a short time until disable is handled from fhem.cfg by fhem and sent over to fhempy_
I think during startup of fhem (in my case once a week in the night) that might be not that bad...

**Comment by pseudex** [comment]
for me it is not a problem if the device is loaded. the device should not try to connect to the local device or the tuya cloud.

**Comment by fhempy** [comment]
Generic disable is now available.

How it works:
 - every module gets a disable 0/1 attribute
 - if you set disable 1, Undefine is called and the device gets unusable
 - if a device is disabled, a warning above the command section in FHEMWB is displayed
 - commands called for disabled devices show an error message, that the command is not available
 - if you set disable 0 or delete the attribute, Define is called and everything works again
 - disable toggle works as well

Please do some tests and let me know if it works for you.

**Comment by fhempy** [comment]
I close this one, please open a new one if something isn't working as expected.
