### ISSUE TITLE
Installation tuya mittels pip

### ISSUE THREAD

**Issue by sidey79** [fhempy/fhempy#122]
Ich habe irgendwie neue Herausforderungen beim erzeugen von Container Images gefunden.

Ich versuche mittels pip install das tuya Modul inkl. Abhängigkeiten zu installieren.
Die Quelle ist folgende aus dem manifest.json, da pip kein manifest.json verarbeitet wandele ich dies in eine requirements.txt Datei um.

Das ganze läuft auf einen Fehler, da durch setup.py letztendlich ein core.py aufgerufen wird, welches das Modul `colorama` voraussetzt.

```
Collecting git+https://github.com/fhempy/tinytuya#tinytuya==1.7.3 (from -r requirements.txt (line 1))
#16 0.651   Cloning https://github.com/fhempy/tinytuya to /tmp/pip-req-build-m93btp90
#16 0.656   Running command git clone --filter=blob:none --quiet https://github.com/fhempy/tinytuya /tmp/pip-req-build-m93btp90
#16 1.778   Resolved https://github.com/fhempy/tinytuya to commit aaf63a1bb292c6f9e171905bfa3ce7324f6e425c
#16 1.780   Preparing metadata (setup.py): started
#16 1.990   Preparing metadata (setup.py): finished with status 'error'
#16 1.998   error: subprocess-exited-with-error
#16 1.998   
#16 1.998   × python setup.py egg_info did not run successfully.
#16 1.998   │ exit code: 1
#16 1.998   ╰─> [10 lines of output]
#16 1.998       Traceback (most recent call last):
#16 1.998         File "<string>", line 2, in <module>
#16 1.998         File "<pip-setuptools-caller>", line 34, in <module>
#16 1.998         File "/tmp/pip-req-build-m93btp90/setup.py", line 3, in <module>
#16 1.998           from tinytuya import __version__
#16 1.998         File "/tmp/pip-req-build-m93btp90/tinytuya/__init__.py", line 92, in <module>
#16 1.998           from .core import *
#16 1.998         File "/tmp/pip-req-build-m93btp90/tinytuya/core.py", line 67, in <module>
#16 1.998           from colorama import init
#16 1.998       ModuleNotFoundError: No module named 'colorama'
#16 1.998       [end of output]
#16 1.998   
#16 1.998   note: This error originates from a subprocess, and is likely not a problem with pip.
#16 2.001 error: metadata-generation-failed
```

Ich bin kein Python experte, vermute aber, es liegt daran, dass zuerst die Metadaten Abruft und erst anschließend die Abhängigkeiten auflöst. Der Abruf der Metadaten klappt nicht.
Möglicherweise kann der Abruf der Metadaten umgangen werden, indem der Name des Projektes angegeben wird.
Dazu müsste die URL laut https://pip.pypa.io/en/stable/topics/vcs-support/ wie folgt angepasst werden:

Ob das Problem dadurch beseitigt wird, habe ich nicht verifiziert, allerdings brauche ich Hilfe, um das Paket von der angegebenen Quelle, also nicht die Version im pip Index, installiert werden kann:

`git+https://github.com/fhempy/tinytuya#egg=tinytuya`

**Comment by fwgerhardt** [comment]
Ich hatte das gleiche Problem. Jetzt funktioniert die Installation. Allerdings 'set tuya_system start_scan' in fhem wird mit 'Command not available for this device.' abgelehnt. Manuell angelegte Devices laufen aber einwandfrei.

**Comment by sidey79** [comment]
Der Fehler ist beseitigt. Jetzt hänge ich an einem Anderen.
Bezüglich der URL. Bist Du dir sicher, dass das die richtige Sytax ist? Denn in der URL ist der packageName nicht wie in der Doku formatiert.

**Comment by fhempy** [comment]
> Ich hatte das gleiche Problem. Jetzt funktioniert die Installation. Allerdings 'set tuya_system start_scan' in fhem wird mit 'Command not available for this device.' abgelehnt. Manuell angelegte Devices laufen aber einwandfrei.

Kannst du das bitte nochmals testen und im fhempy Log schauen ob ein Fehler auftritt?

**Comment by fhempy** [comment]
> Der Fehler ist beseitigt. Jetzt hänge ich an einem Anderen. Bezüglich der URL. Bist Du dir sicher, dass das die richtige Sytax ist? Denn in der URL ist der packageName nicht wie in der Doku formatiert.

Ich nutze die gleiche Syntax wie Home Assistant:
https://developers.home-assistant.io/docs/creating_integration_manifest/#custom-requirements-during-development--testing

**Comment by fwgerhardt** [comment]
Das ist das Log nach einem Device Scan:

`2023-01-19 19:29:18,113 - ERROR    - tuya_system: Exception raised by task: <Task finished name='Task-761' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py:194> exception=KeyError('result')>
Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 202, in _handle_task_result
    task.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/generic.py", line 196, in _run_coro
    await coro
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 704, in _scan_devices
    for i in json_data["result"]:
KeyError: 'result'`

**Comment by fhempy** [comment]
Dein api Key/Secret ist hinterlegt und korrekt?

**Comment by fwgerhardt** [comment]
Ist korrekt und funktioniert wenn ich die Devices manuell anlege.

 

Von: Dominik ***@***.***> 
Gesendet: Donnerstag, 19. Januar 2023 19:46
An: fhempy/fhempy ***@***.***>
Cc: fwgerhardt ***@***.***>; Comment ***@***.***>
Betreff: Re: [fhempy/fhempy] Installation tuya mittels pip (Issue #122)

 

Dein api Key/Secret ist hinterlegt und korrekt?

**Comment by fhempy** [comment]
Teste es bitte mit der aktuellen fhempy Version. Ich habe noch eine bessere Fehlerhandhabung eingebaut. Nun solltest du im Log und state Reading sehen was der Fehler ist.

**Comment by fwgerhardt** [comment]
Seltsam:
`2023-01-19 22:24:47,373 - ERROR    - tuya_system: getdevices: {'Error': 'Error Response from Tuya Cloud', 'Err': '913', 'Payload': "Error from Tuya Cloud: Code 28841002: 'No permissions. Your subscription to cloud development plan has expired.'"}`

Mein App Account sieht normal aus. Ist erst am 11.12.2022 eingerichtet, damit sollte er nicht expired sein.

**Comment by fhempy** [comment]
Es gab schon Meldungen, dass die nur mehr 1 Monat gültig bleiben. Schau mal auf der Plattform nach, da sollte man einen Antrag auf Verlängerung machen können.

Ich mach das Issue damit hier zu, solltest du noch weitere Unterstützung wg. der Subscription benötigen, bitte gerne ein neues Issue dafür aufmachen.
