### ISSUE TITLE
EQ3BT -> Problems?

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#125]
Hey there,
I'm getting this here in fhempy on a client (zero-w):
`Jan 23 20:55:41 ZeroW fhempy[514]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/core/bluetoothle.py", line 126, in connect_once
Jan 23 20:55:41 ZeroW fhempy[514]:     await self._client.connect()
Jan 23 20:55:41 ZeroW fhempy[514]:   File "/home/pi/.local/lib/python3.9/site-packages/bleak/__init__.py", line 471, in connect
Jan 23 20:55:41 ZeroW fhempy[514]:     return await self._backend.connect(**kwargs)
Jan 23 20:55:41 ZeroW fhempy[514]:   File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/client.py", line 190, in connect
Jan 23 20:55:41 ZeroW fhempy[514]:     assert_reply(reply)
Jan 23 20:55:41 ZeroW fhempy[514]:   File "/home/pi/.local/lib/python3.9/site-packages/bleak/backends/bluezdbus/utils.py", line 20, in assert_reply
Jan 23 20:55:41 ZeroW fhempy[514]:     raise BleakDBusError(reply.error_name, reply.body)
Jan 23 20:55:41 ZeroW fhempy[514]: bleak.exc.BleakDBusError: [org.bluez.Error.Failed] Software caused connection abort
`

What is the cause here? Wrong python?

**Comment by fhempy** [comment]
Hi,
please repair the device:
https://github.com/rytilahti/python-eq3bt#pairing

After that do
```
sudo systemctl restart bluetooth
sudo hciconfig hci0 down
sudo hciconfig hci0 reset
sudo hciconfig hci0 up
```

Check if it works afterwards.

**Comment by JorinL** [comment]
Mhh never had to pair them - did no fw update on them.
There was always the saying to not do it so the communication works.

Did something change? Do I have to update?

**Comment by fhempy** [comment]
The change was the Bluetooth library I'm using. I used bluepy before which is not maintained any more, therefore I switched to bleak. It's more stable and under active development.

You do not need to update the firmware.

**Comment by JorinL** [comment]
But pairing is needed?

Must I reinstall my fhempy? Or uninstall something?

**Comment by fhempy** [comment]
Just follow the steps I mentioned above, that's it.

**Comment by JorinL** [comment]
Hehe ok - yeah currently away from home.

Thx for your quick support.
Enjoyed like ever.

**Comment by JorinL** [comment]
Seemed like, the newest version was not installed - also if update was triggered out of FHEM.
Installed it now manually:

`Installing collected packages: fhempy
  Attempting uninstall: fhempy
    Found existing installation: fhempy 0.1.570
    Uninstalling fhempy-0.1.570:
      Successfully uninstalled fhempy-0.1.570
Successfully installed fhempy-0.1.571`

**Comment by fhempy** [comment]
Could be that it wasn't available at pypi at the time of the update.

Btw, you can do the steps mentioned above also if you are away from home. It doesn't require any changes on the thermostat. You don't need to press the button for pairing either.

**Comment by fhempy** [comment]
Try to restart bluetooth before

**Comment by JorinL** [comment]
Sadly does not change that:

```
pi@ZeroW:~ $ sudo systemctl restart bluetooth
pi@ZeroW:~ $ sudo bluetoothctl
Agent registered
[CHG] Controller B8:27:EB:34:B6:95 Pairable: yes
[bluetooth]# default-agent
Default agent request successful
[bluetooth]# pair 00:1A:22:0C:1A:47
Attempting to pair with 00:1A:22:0C:1A:47
[CHG] Device 00:1A:22:0C:1A:47 Connected: yes
Failed to pair: org.bluez.Error.ConnectionAttemptFailed
[CHG] Device 00:1A:22:0C:1A:47 Connected: no
```

**Comment by JorinL** [comment]
Did:

```
pi@ZeroW:~ $ sudo systemctl restart bluetooth
pi@ZeroW:~ $ sudo bluetoothctl
Agent registered
[CHG] Controller B8:27:EB:34:B6:95 Pairable: yes
[bluetooth]# power on
Changing power on succeeded
[bluetooth]# agent on
Agent is already registered
[bluetooth]# default-agent
Default agent request successful
[bluetooth]# scan on
Discovery started
[CHG] Controller B8:27:EB:34:B6:95 Discovering: yes
[NEW] Device 41:C2:34:EA:CD:21 41-C2-34-EA-CD-21
[NEW] Device 36:FE:73:F0:57:B9 36-FE-73-F0-57-B9
[NEW] Device FC:03:9F:1F:F6:8D FC-03-9F-1F-F6-8D
[NEW] Device 3C:61:7C:64:4F:18 3C-61-7C-64-4F-18
[NEW] Device 62:CE:3A:AB:70:BA 62-CE-3A-AB-70-BA
[CHG] Device 00:1A:22:0C:1A:47 RSSI: -77
[CHG] Device 00:1A:22:0C:1A:47 UUIDs: 3e135142-654f-9090-134a-a6ff5bb77046
[CHG] Device 00:1A:22:0C:F5:AE RSSI: -74
[NEW] Device 57:60:1E:3D:1D:91 57-60-1E-3D-1D-91
[NEW] Device 41:FB:F2:50:43:A2 41-FB-F2-50-43-A2
[CHG] Device 00:1A:22:0C:18:D4 RSSI: -82
[CHG] Device 00:1A:22:0C:18:D4 UUIDs: 3e135142-654f-9090-134a-a6ff5bb77046
[NEW] Device 00:1A:22:0C:F5:41 CC-RT-BLE
[NEW] Device 63:F3:EA:62:C0:20 63-F3-EA-62-C0-20
[NEW] Device 60:1E:72:97:8F:49 60-1E-72-97-8F-49
[NEW] Device 63:03:2A:38:AB:2C 63-03-2A-38-AB-2C
[CHG] Device 00:1A:22:0C:E8:EA RSSI: -81
[CHG] Device 00:1A:22:0C:E8:EA UUIDs: 3e135142-654f-9090-134a-a6ff5bb77046
[NEW] Device 51:D9:94:75:79:4B 51-D9-94-75-79-4B
[bluetooth]# scan off
Discovery stopped
[CHG] Device 51:D9:94:75:79:4B TxPower is nil
[CHG] Device 51:D9:94:75:79:4B RSSI is nil
[CHG] Device 00:1A:22:0C:E8:EA RSSI is nil
[CHG] Device 63:03:2A:38:AB:2C TxPower is nil
[CHG] Device 63:03:2A:38:AB:2C RSSI is nil
[CHG] Device 60:1E:72:97:8F:49 TxPower is nil
[CHG] Device 60:1E:72:97:8F:49 RSSI is nil
[CHG] Device 63:F3:EA:62:C0:20 TxPower is nil
[CHG] Device 63:F3:EA:62:C0:20 RSSI is nil
[CHG] Device 00:1A:22:0C:F5:41 RSSI is nil
[CHG] Device 00:1A:22:0C:18:D4 RSSI is nil
[CHG] Device 41:FB:F2:50:43:A2 RSSI is nil
[CHG] Device 57:60:1E:3D:1D:91 TxPower is nil
[CHG] Device 57:60:1E:3D:1D:91 RSSI is nil
[CHG] Device 00:1A:22:0C:F5:AE RSSI is nil
[CHG] Device 00:1A:22:0C:1A:47 RSSI is nil
[CHG] Device 62:CE:3A:AB:70:BA TxPower is nil
[CHG] Device 62:CE:3A:AB:70:BA RSSI is nil
[CHG] Device 3C:61:7C:64:4F:18 RSSI is nil
[CHG] Device FC:03:9F:1F:F6:8D RSSI is nil
[CHG] Device 36:FE:73:F0:57:B9 RSSI is nil
[CHG] Device 41:C2:34:EA:CD:21 TxPower is nil
[CHG] Device 41:C2:34:EA:CD:21 RSSI is nil
[CHG] Controller B8:27:EB:34:B6:95 Discovering: no
[bluetooth]# pair 00:1A:22:0C:1A:47
Attempting to pair with 00:1A:22:0C:1A:47
[CHG] Device 00:1A:22:0C:1A:47 Connected: yes
Failed to pair: org.bluez.Error.ConnectionAttemptFailed
[CHG] Device 00:1A:22:0C:1A:47 Connected: no
[bluetooth]# trust 00:1A:22:0C:1A:47
Changing 00:1A:22:0C:1A:47 trust succeeded
[DEL] Device 3C:61:7C:64:4F:18 3C-61-7C-64-4F-18
[DEL] Device FC:03:9F:1F:F6:8D FC-03-9F-1F-F6-8D
[DEL] Device 00:1A:22:0C:F5:41 CC-RT-BLE
[DEL] Device 36:FE:73:F0:57:B9 36-FE-73-F0-57-B9
[DEL] Device 41:FB:F2:50:43:A2 41-FB-F2-50-43-A2
[DEL] Device 63:F3:EA:62:C0:20 63-F3-EA-62-C0-20
[DEL] Device 62:CE:3A:AB:70:BA 62-CE-3A-AB-70-BA
[DEL] Device 60:1E:72:97:8F:49 60-1E-72-97-8F-49
[DEL] Device 41:C2:34:EA:CD:21 41-C2-34-EA-CD-21
[DEL] Device 63:03:2A:38:AB:2C 63-03-2A-38-AB-2C
[DEL] Device 51:D9:94:75:79:4B 51-D9-94-75-79-4B
[DEL] Device 57:60:1E:3D:1D:91 57-60-1E-3D-1D-91
[bluetooth]# disconnect 00:1A:22:0C:1A:47
Attempting to disconnect from 00:1A:22:0C:1A:47
Successful disconnected
[bluetooth]# pair 00:1A:22:0C:1A:47
Attempting to pair with 00:1A:22:0C:1A:47
[CHG] Device 00:1A:22:0C:1A:47 Connected: yes
Failed to pair: org.bluez.Error.ConnectionAttemptFailed
[CHG] Device 00:1A:22:0C:1A:47 Connected: no
[bluetooth]# exit

```

**Comment by fhempy** [comment]
Hmm...maybe you still need to press the button on the thermostat.

**Comment by JorinL** [comment]
Yep - that is what I think.

But no problem :-) Will do when I'm back.

So did I get that right?
I can also update to the newest firmware?

**Comment by fhempy** [comment]
I think so - I never tried it 😄

**Comment by JorinL** [comment]
Hehe - is there a way to "downgrade" again?

Or am I eventually bricking one?

**Comment by fhempy** [comment]
Afaik there is no downgrade. It should work with firmware version above 120 as other users in Home Assistant, which use the same library, reported it.

**Comment by JorinL** [comment]
Which bluez version should be installed?
Is it a pip oder an apt thing?

**Comment by fhempy** [comment]
apt, just update to the latest one which is available in bullseye.

**Comment by JorinL** [comment]
Check.

So I will head back here when home an check it out with pairing.

So we can adjust this:

```
EQ3 Bluetooth Thermostat
This module is used to control EQ3 Bluetooth thermostats.

Attention: Firmware version 120 is recommended, do not install the newest calor BT firmware! Newer firmwares won't work with this module.
```

**Comment by JorinL** [comment]
"Pairing successful"

without FW upgrade and without pin - old 1.20 FW. :-)

Reinstalled the zeroW new and fhempy.
Took a while to upgrade itself and now it is working like ever :-)

Thanks! -> Solved.

Will see if I upgrade to the higher ^^ - Risky... eventually

I found also out, that is started working without the pairing - did see that while paring the first. Some others where already doing stuff. :-D

**Comment by fhempy** [comment]
Please delete the presence reading. It's not in use any more as connection reading keeps track of the state.

**Comment by JorinL** [comment]
Wow that is impressive reactive.
Really "Instant" they react on changes.

Is there an outlook for having the fhempy peer running on ubuntu and others? ;-)
Currently it throws errors on that.

I use an Intel Nuc as Homeserver - which also has Bluetooth inside. If it would work on Ubuntu I could retire the ZeroW Pi :-)

Nice work at all - thanks for time and support.
This can be closed :-)

**Comment by fhempy** [comment]
Thanks for your feedback!

Feel free to open an issue regarding Ubuntu so that I can have a look into it.
