### ISSUE TITLE
Ledvance WiFi Smartplug with energy metering

### ISSUE THREAD

**Issue by AlexMuc2** [fhempy/fhempy#128]
Hi all,
Ive got the smart plug from the Tonic and added it with this ID **j0zozzoarutv0nu1** to fhempy. 
A test with TinyTuya reveals, that this smart plug doesn't return the "46" Value as we can see in this sample:
set_status() result {'dps': {'1': False, '9': 0, '17': 16, '18': 0, '19': 0, '20': 2269, '21': 1, '22': 1578, '23': 39846, '24': 108000, '25': 380, '26': 0, '38': 'on', '41': '', '42': ''}}
The ID "j0zozzoarutv0nu1" seems the nearest match for this plug and all values other values seems fine.

Is it possible to  add this plug in the mappings.py file as a new "knownSchemas"?

Michael

**Comment by fhempy** [comment]
Hi,
adding the productid to the mappings.py file wouldn't change the behavior. What do you expect to get from DP 46?

**Comment by AlexMuc2** [comment]
Hi Dominic,
no, the Ledvance does not have the DP46 as you can see in the result. For this Ledvance Wifi Plug it should be removed. The j0zozzoarutv0nu1 was the nearest match I’ve found.
So a new product ID is only for other users which don’t know which is they should use for this plug.

**Comment by fhempy** [comment]
Ok, got it. If you provide me the productid of your smart plug, I can add it as a separate schema to mappings.py.

**Comment by AlexMuc2** [comment]
:-) do you have a hint where I can find this ID? I‘ve searched everything, but haven’t found this ID. Is there a command that I can use with tinytuya to help xtract the ID? The „virtual ID“ is the only I’d the Ledvanceapp is showing but that one.
If it helps, this is the define in fhem:
defmod plug_LedvanceMeter1 fhempy tuya 0fHWRe8ULjtmnBNd bffc34ecf456326979mzl0 maskedDeviceIP af4e23037768a2c0

**Comment by fhempy** [comment]
Just set up tuya_cloud as mentioned in the readme. If you provide API_KEY/SECRET the productid is automatically retrieved from the tuya iot cloud.

**Comment by AlexMuc2** [comment]
But I don’t have this Api_Key and secret. Ledvance seems doing it‘s own (hidden) thing and I’ve found no way to use the tuya iot cloud/ App. I can use only the Ledvance App or tinyTuya. Ledvance uses it‘s own cloud :-(

**Comment by fhempy** [comment]
Oh, I didn't know that. How did you retrieve the local key for that device?

I can create a "ledvance_smartplug_with_energy" productid in that case.

**Comment by AlexMuc2** [comment]
The local key was simple. TinyTuya will show it when it scans for devices. I don’t know any way to retrieve the product ID. Perhaps someone with more knowledge can examine the Ledvance app. If tinyTuya can extrakt the ID than I will try it. Otherwise you have to create a new ID yourself if that’s possible.

**Comment by fhempy** [comment]
Ok, I'm going to add a product id ledvance_smartplug_energy, that's the easiest solution.

**Comment by AlexMuc2** [comment]
Thanks a lot. This makes life easier for others if they add this plug or Fhem.

**Comment by AlexMuc2** [comment]
Hopefully final update how to extract ProductKey and localKey for the "Ledvance WiFi smartplug with smart metering"
So, after a lookup at my notes here is the the Way how to Retriever the localkey and the productID from Ledvance:
The script from link https://github.com/FlagX/ha-ledvance-tuya-resync-localkey will extract the devicename, device ID and local key from the Ledvance Cloud. Keep in mind, that your device hold be visible in the LedvanceApp.

Now installiert TinyTuya from here https://pypi.org/project/tinytuya/ and with this command from the Terminal (python -m tinytuya scan) you get a device List. If the Output contains "Found x device(es)" and "Saving device snapshot data to snapshot.json" you can find the proper productkey with cat snapshot.json from the Terminal.

The produktKey for Ledvance WiFi smartplug is "keym9qkuywghyrvs". This shoud be added to the file mappings.py.
Getting the Status of the device with tinyTuya reveals this usedDS (could't be, that there are some more for Countdowns (DPs 9 to 15) but this is unproofed by me.
This is the Status from my device:
Device status: {'dps': {'1': True, '9': 0, '17': 13, '18': 34, '19': 31, '20': 2291, '21': 1, '22': 1578, '23': 39846, '24': 108000, '25': 380, '26': 0, '38': 'memory', '41': '', '42': ''}}
the meaning of all DPs are described here https://github.com/jasonacox/tinytuya#version-33---plug-switch-power-strip-type.

Hopefully someone can check this.

**Comment by fhempy** [comment]
Productid keym9qkuywghyrvs added to mappings.py.

Please check if it works. Thx!

**Comment by AlexMuc2** [comment]
Seems working until now :-)
Thank you very much
