### ISSUE TITLE
special characters in readings and device names 

### ISSUE THREAD

**Issue by FrankBungarten** [fhempy/fhempy#156]
Hallo Dominik,
anscheinend existiert noch Bug bei den readings.

Ich habe zwei neue BOEK Heizungtermostat (eins konnte ich anlegen das zweite nicht). Ich bekomme die Fehlermeldung

"Failed to execute function Define: Traceback (most recent call last): File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function ret = await self.execute_function(hash, fhem_reply_done, nmInstance) File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/fhem_pythonbinding.py", line 486, in execute_function fct_timeout, File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for return fut.result() File "/opt/fhem/.local/lib/python3.7/site-packages/fhempy/lib/tuya/tuya.py", line 66, in Define self.tt_version = float(args[7]) ValueError: could not convert string to float: '362cc5bdf2454924bc740881a76xyzbb"

Der Fehler tritt beim define auf

define EG.Test.RaumThermostat fhempy tuya gw173aldekvpzalg bf0c20196aa9841ec9XYZZ 192.168.5.18 !'?=Iu'Tq;%o-}Q'  API_KEY API_SECRET

Und zwar taucht zuerst der Fehler beim LOCAL_KEY auf. Dieser wird nur vekürzt übernommen und der Rest wird abgeschnitten.  Danach über modify DEF die Daten ergänzt kommt es zu der obigen Fehlermeldung.

Das Termostat selber habe ich in der TUYA Applikation und in der Tuya Cloud schon resetet,gelöscht und neu angelegt. Insg. zweimal. Der Fehler bleibt.

Gruß Frank

**Comment by FrankBungarten** [comment]
Hallo Dominik,
noch eine Ergänzung, Ich habe heute das BEOK mehrfach zurückgesetzt und habe letztendlich einen LOCAL_KEY ohne "Hochkomma ' " bekommen. Siehe da es funktioniert.  Da wird die Ursache für den Fehler sein.
Gruß Frank

**Comment by fhempy** [comment]
Hallo Frank,

danke dir für die Info! Ich werde das beheben, muss dazu wahrscheinlich das Define anpassen. Im Define funktionieren die Special Characters leider nicht und das führt zu den Problemen. Ich werde den local key als Attribut anlegen.

**Comment by fhempy** [comment]
Sollte nun wieder funktionieren 👍
