### ISSUE TITLE
ble presence funktioniert nicht mehr

### ISSUE THREAD

**Issue by DB1113** [fhempy/fhempy#161]
Moin,

nach einem Update des Pi funktioniert das ble_presence leider nicht mehr.
Im Log habe ich folgende Meldung:
`2023-06-08 00:00:05,774 - WARNING  - bluetooth_auto_recovery.recover: Bluetooth adapter hci0 [3A:XX:XX:XX:XX:AF] could not be reset due to timeout
2023-06-08 00:00:05,807 - WARNING  - bluetooth_auto_recovery.recover: Bluetooth management socket connection lost: [Errno 9] Bad file descriptor`

Die Meldung kommt in unregelmäßigen Abständen wieder.
Das state der Devices wird genau ein Mal gesetzt: beim Hochfahren des Pi. Danach gibt es keine Aktualisierung der Devices mehr.

Bis denn
DB

**Comment by fhempy** [comment]
Hi,
kannst du bitte ein hciconfig -a machen wenn es nicht funktioniert.

**Comment by DB1113** [comment]
Hi,
jetzt endlich... sorry!
` hciconfig -a
hci0:   Type: Primary  Bus: USB
        BD Address: 3A:81:D0:7E:EB:AF  ACL MTU: 310:10  SCO MTU: 64:8
        UP RUNNING
        RX bytes:7203172 acl:40 sco:0 events:206518 errors:0
        TX bytes:23209 acl:42 sco:0 commands:2864 errors:0
        Features: 0xff 0xff 0x8f 0xfe 0xdb 0xff 0x5b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH HOLD SNIFF PARK
        Link mode: SLAVE ACCEPT
        Name: 'fhemRasPi4'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous,
        HCI Version: 4.0 (0x6)  Revision: 0x22bb
        LMP Version: 4.0 (0x6)  Subversion: 0x22bb
        Manufacturer: Cambridge Silicon Radio (10)
`

mehr kommt da nicht.

Bis denn

**Comment by fhempy** [comment]
Das ist ein externer Dongle, oder? Blöde Frage, aber hast du ihn auch schon mal abgesteckt und wieder neu angesteckt?

**Comment by DB1113** [comment]
Moin,
ja, ich hab ihn jetzt abgesteckt und angesteckt sowie danach durch einen anderen (baugleichen) Dongle ersetzt...
Keine Besserung. :(

Bis denn

**Comment by DB1113** [comment]
Ich zieh alles zurück und behaupte das Gegenteil...
Ich habe nicht erkannt, dass ein G-tag defekt war und zusätzlich bei einem anderen noch die Batt. leer.
Habe mit dem (unerkannt) defektem Gerät rumhantiert, in der Annahme, dass sich die Ergebnisse auf beide G-tags spiegeln lassen. 
Nachdem ich jetzt feststellen durfte, dass der G-tag im Eimer ist und die bei dem Anderen die Batt. getauscht ist, habe ich keine Beanstandungen mehr :)

Sorry!

**Comment by DB1113** [comment]
Sorry, ich muss da doch noch mal ran.

Habe hier jetzt zwei definitiv funktionierende!! G-Tags.
Nach einem fhem-Neustart funktioniert die Anwesenheitserkennung.
Nach einer mir nicht bekannten Zeit aber nicht mehr.

List vom Device:
`Internals:
   DEF        ble_presence 7C:2F:80:xxx
   FHEMPYTYPE ble_presence
   FUUID      64992e0e-f33f-7c83-3417-a553a6d808ffc075
   FVERSION   10_fhempy.pm:0.182830/2019-01-16
   IODev      [pyBinding]
   MAC        7C:2F:80:xxx
   NAME       [Gtag]
   NR         795
   PYTHONTYPE ble_presence
   STATE      present
   TYPE       fhempy
   eventCount 64
   READINGS:
     2023-06-26 10:04:58   battery         100
     2023-06-26 10:04:48   name            Gigaset G-tag
     2023-08-10 00:03:38   presence        present
     2023-08-10 00:03:38   rssi            -71
     2023-08-10 00:03:38   state           present
   args:
     [Gtag]
     fhempy
     ble_presence
     7C:2F:80:xxx
   argsh:
Attributes:
   alias      G-tag
   event-on-change-reading state,presence,battery
   group      ble_presence
   read_characteristics battery
   room       Residents,fhempy`

Hast du noch Vorschläge, woran das liegen kann?
Funktioniert das ble presence bei dir?

Thx und bis denn

**Comment by fhempy** [comment]
Hi,
kannst du bitte freezemon in FHEM installieren und prüfen ob FHEM ab und zu lange blockiert? Die "FHEM took ...ms" deuten nämlich darauf hin.
