### ISSUE TITLE
Googlecast Fehlermeldung (TypeError) / falsche Logfilenamen

### ISSUE THREAD

**Issue by bublath** [fhempy/fhempy#169]
Wenn ich auf in FHEM das googlecast Device meines GoogleNest öffne, dann bekomme ich die Fehlermeldung:
```
fhem?detail=GoogleWohnzimmer line 218:
Uncaught TypeError: Cannot set properties of undefined (setting 'innerHTML')
```

Gerade komplettes FHEM update inkl. fhempy gemacht. Hat nichts verändert.
Das Device an sich funktioniert halbwegs: Ich kann per set volume die Lautstärke ändern. Ein "set speak" führt allerdings zu keiner Reaktions seitens Google.

Bei der Gelegenheit eine Kleinigkeit:
Ich hab meine gassistant logfiles auf monatsfein umgestellt (./log/gassistant-%Y-%m.log). Es werden aber trotzdem noch zusätzlich (leere) tagesfeine Logfiles angelegt.
Bei fhempy ist es noch schlimmer: Hier habe ich ein Jahresfile eingestellt (./log/fhempy-%Y.log Logfile).
Dieses wird zwar angelegt, hat aber immer 0 Bytes, wogegen die eigentlichen Daten weiter in den tagesfeinen Logs landen.

**Comment by fhempy** [comment]
Hi,
hast du eventuell den Skin geändert? Tritt der Fehler bei allen fhempy Devices auf?

Wg. Logfile, du hast das Attribut logfile im Device fhempyserver_15733 geändert, oder? Was erscheint danach bei "currentlogfile"?

**Comment by bublath** [comment]
Ich verwendet den normalen f18 und hab lediglich das anpinnen aktiviert - sonst Standard.
Passiert bei allen fhempy devices. Hab jetzt testweise mal ein google_weather neu angelegt und hatte sofort die selbe Meldung.

Beim fhempyserver stimmte das currentlog nicht dem dem erzeugten Filelog device überein. Hab ich jetzt nochmal neu gesetzt - jetzt stimmt es überein. Das muss aber irgendwann mal divergiert sein, bin mir aber nicht sicher - ist schon ewig her.
Bei gassistant ähnlich. Muss ich jetzt mal beobachten - vielleicht war das auch mein Fehler.
