### ISSUE TITLE
Ring Intercom: "device not found"

### ISSUE THREAD

**Issue by hailigsblechle** [fhempy/fhempy#178]
Hi team,

I've just installed fhempy and wanted to connect it to my new Ring "Intercom" device. After successfully setting the password and 2fa, the state is showing FHEM STATE is showing "device not found".

Is the Ring intercom not yet supported or is something not configured correctly yet?

Thank and best regards
hailigsblechle

**Comment by fhempy** [comment]
Hi,

unfortunately it's currently not supported in the ring library I use in fhempy. Nevertheless a pull request was already opened for it, see https://github.com/tchellomello/python-ring-doorbell/pull/277

**Comment by fhempy** [comment]
library update with intercom support is available. It's not yet updated in fhempy.
