### ISSUE TITLE
ModuleNotFoundError: No module named 'bs4' / No module named 'JWT'

### ISSUE THREAD

**Issue by SiggiBS** [fhempy/fhempy#182]
I had  some issues while the installation of skodaconnect  in a fhem docker environment because the modules bs4 and jwt were missing. This was documented by some fhempy server Log entries. 

Meanwhile I helped myself an execute the following  statements 

pip3 install PyJWT
pip install BeautifulSoup4

Now I could get connected to my car

**Comment by fhempy** [comment]
PyJWT and BeautifulSoup4 are both included in the skodaconnect package:
https://github.com/skodaconnect/skodaconnect/blob/main/requirements.txt

Can you please verify if both packages are installed if you just do
pip3 install skodaconnect

**Comment by SiggiBS** [comment]
Hi, yes, now everything works fine. Thx.
