### ISSUE TITLE
This package requires Rust >=1.56.0

### ISSUE THREAD

**Issue by jowiemann** [fhempy/fhempy#184]
Hallo,

ich habe regelmäßig im fhempy...log den Versuch "wheel for cryptography" zu bauen. Dieser scheitert mit dem Hinweis:

error: can't find Rust compiler
...
This package requires Rust >=1.56.0

Ich habe Rust unter /opt/rust installiert und $PATH ist so angepasst, dass auch der System-User fhem darauf zugreifen kann.

fhem@raspberrypi:/home/pi$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/openjdk17/bin:/opt/rust/bin

Habt ihr noch eine Idee, wie ich das "can't find Rust compiler" lösen kann?

Grüße Jörg

**Comment by fhempy** [comment]
Hi Jörg,

welches Modul verwendest du wo cryptography versucht wird zu bauen? In der Basisinstallation habe ich nämlich cryptography entfernt.

**Comment by jowiemann** [comment]
Hallo Dominik,vielen Dank für die Rückmeldung. Ich nutze skodaconnect.Liebe Grüße Jörg Von meinem iPhone gesendetAm 26.08.2023 um 23:27 schrieb Dominik ***@***.***>:﻿
Hi Jörg,
welches Modul verwendest du wo cryptography versucht wird zu bauen? In der Basisinstallation habe ich nämlich cryptography entfernt.

**Comment by fhempy** [comment]
Poste bitte mal den Output von
```
sudo -u fhem bash
pip3 install skodaconnect
```

**Comment by jowiemann** [comment]
***@***.***:~ $ sudo -u fhem bash
***@***.***:/home/pi$ pip3 install skodaconnect
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: skodaconnect in /opt/fhem/.local/lib/python3.9/si                                                                             te-packages (1.3.6)
Requirement already satisfied: aiohttp in /opt/fhem/.local/lib/python3.9/site-pa                                                                             ckages (from skodaconnect) (3.8.5)
Requirement already satisfied: beautifulsoup4 in /opt/fhem/.local/lib/python3.9/                                                                             site-packages (from skodaconnect) (4.11.2)
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (f                                                                             rom skodaconnect) (3.3.2)
Requirement already satisfied: lxml in /opt/fhem/.local/lib/python3.9/site-packa                                                                             ges (from skodaconnect) (4.9.2)
Requirement already satisfied: pyjwt in /opt/fhem/.local/lib/python3.9/site-pack                                                                             ages (from skodaconnect) (2.6.0)
Requirement already satisfied: attrs>=17.3.0 in /opt/fhem/.local/lib/python3.9/s                                                                             ite-packages (from aiohttp->skodaconnect) (22.2.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in /opt/fhem/.local/                                                                             lib/python3.9/site-packages (from aiohttp->skodaconnect) (2.0.12)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/fhem/.local/lib/pytho                                                                             n3.9/site-packages (from aiohttp->skodaconnect) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in /opt/fhem/.local/l                                                                             ib/python3.9/site-packages (from aiohttp->skodaconnect) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in /opt/fhem/.local/lib/python3.9/                                                                             site-packages (from aiohttp->skodaconnect) (1.8.2)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/fhem/.local/lib/python3                                                                             .9/site-packages (from aiohttp->skodaconnect) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/fhem/.local/lib/python3.                                                                             9/site-packages (from aiohttp->skodaconnect) (1.3.1)
Requirement already satisfied: soupsieve>1.2 in /opt/fhem/.local/lib/python3.9/s                                                                             ite-packages (from beautifulsoup4->skodaconnect) (2.4)
Requirement already satisfied: idna>=2.0 in /usr/lib/python3/dist-packages (from yarl<2.0,>=1.0->aiohttp->skodaconnect) (2.10)

Grüße Jörg


Von: Dominik
Gesendet: Sonntag, 27. August 2023 17:47
An: fhempy/fhempy
Cc: jowiemann; Author
Betreff: Re: [fhempy/fhempy] This package requires Rust >=1.56.0 (Issue #184)

Poste bitte mal den Output von
sudo -u fhem bash
pip3 install skodaconnect

**Comment by fhempy** [comment]
Hi,
bitte mit der letzten fhempy Version testen. Danke!

**Comment by jowiemann** [comment]
Hallo Dominik,

 

sieht gut aus. Danke Dir.

 

Grüße Jörg

 

Von: Dominik ***@***.***> 
Gesendet: Samstag, 9. September 2023 20:40
An: fhempy/fhempy ***@***.***>
Cc: jowiemann ***@***.***>; Author ***@***.***>
Betreff: Re: [fhempy/fhempy] This package requires Rust >=1.56.0 (Issue #184)

 

Hi,
bitte mit der letzten fhempy Version testen. Danke!
