### ISSUE TITLE
wienernetze_smartmeter - Hide login data

### ISSUE THREAD

**Issue by drhirn** [fhempy/fhempy#189]
When using the wienernetze_smartmeter plugin username/password are shown in plain text in FHEM. Not very good.
Is there a way to store them in `FHEM/FhemUtils/uniqueID` file or anywhere else?

**Comment by fhempy** [comment]
I planned to implement an encryption for sensitive data but it's not yet implemented. The encryption will be done with the uniqueid from FHEM.
