### ISSUE TITLE
Beok WiFi Thermostat (TDR89WIFI-WP) no update temp_set if you change the temperatur manually via Display

### ISSUE THREAD

**Issue by FrankBungarten** [fhempy/fhempy#200]
Hi Dominik,
I m´t not sure if it is a bug or a feature. As long as the BEOK has a connection to the Internet and to the Cloud you can  change the temperatur manually via Display and the readings in FHEM (temp_set) change also. But if block the connection to the Internet and change  manually the temperatur via the Display you will get no  updates of the readings FHEM (temp_set).

If you change it via FHEM (set command xxx temp_set) the readings will change in both cases.

I saw same with the following readings:
 - dp_101
 - dp_26
 - dp_41

Additional the readings of the variable switch does even not change if you have an Internet connection to the tuya cloud.

Interesent is if you have a connection to the internet/tuya cloud the BEOK  will sent and gets data every minutes.

tcpdump:
Source			Port	Destination		Port	Proto.	Len	Info
192.168.5.20	40996	3.65.95.68		8886	TLSv1.2	235	Application Data
  3.65.95.68	8886	192.168.5.20	40996	TLSv1.2	123	Application Data
192.168.5.20	40996	3.65.95.68		8886	TCP	54	40996 → 8886 [ACK] Seq=182 Ack=70 Win=2023 Len=0

If the BEOK can´t reach the IP address 3.65.95.68 it try to connect (what I see in a 6 minutes tcp-dump) the following IPs 35.156.42.116; 52.28.144.124; 3.123.124.46; 3.64.85.28; 18.192.43.219.

Regards Frank

**Comment by fhempy** [comment]
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.

Can you try to run tuya (local) and see if that works for your use case?

**Comment by FrankBungarten** [comment]
Hi Dominik,I use the Tuya device locally without an internet connection. After the setup I disconnected the internet connection for this devices. After that most readings gets update. At the moment I am 8000km away from home but I attached the reading from one device. Like I wrote it is only if you manually change the temperature via display. Regards Frank DeviceOverviewEG.WZ.RaumThermostatonoffEG.WZ.RaumThermostatchild_lock mode off on temp_set InternalsDEFReadingsactive_time16810420232023-05-18 22:17:00biz_type02023-05-18 22:17:00categorywk2023-05-18 22:17:00child_lockoff2023-05-18 22:17:00create_time16810406712023-05-18 22:17:00dp_0502023-10-28 11:10:05dp_10102023-05-18 22:17:00dp_105102023-10-17 18:25:54dp_107352023-05-18 22:17:00dp_1312023-05-18 22:17:00dp_1602023-05-18 22:17:00dp_20-202023-10-17 18:25:54dp_21602023-10-17 18:25:54dp_2512023-05-18 22:17:00dp_2602023-10-17 18:25:54dp_3102023-10-17 18:25:54dp_4132023-10-17 18:25:54dp_4212023-05-18 22:17:00dp_43BgAAyAgAAKALHB4AoBEAANwWAACgCAAA3BcAAKA=2023-10-17 18:25:54iconsmart/program_category_icon/wk.png2023-05-18 22:17:00idbfe26ef2023-05-18 22:17:00ip2023-05-18 22:17:00lat50.88252023-05-18 22:17:00local_key2023-05-18 22:17:00lon6.85622023-05-18 22:17:00modecold2023-10-05 08:19:07modelTemp2023-05-18 22:17:00nameWohnzimmer2023-05-18 22:17:00online12023-10-28 11:06:45owner_id1532670422023-05-18 22:17:00product_idgw173a2023-05-18 22:17:00product_nameTemp2023-05-18 22:17:00stateon2023-11-03 02:00:01sub02023-05-18 22:17:00switchon2023-10-01 21:12:26temp_current17.42023-11-12 22:16:58temp_set14.02023-10-31 18:00:00time_zone+02:00Am 10.11.2023 16:48 schrieb Dominik ***@***.***>:
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.
Can you try to run tuya (local) and see if that works for your use case?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 10.11.2023 16:48 schrieb Dominik ***@***.***>:
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.
Can you try to run tuya (local) and see if that works for your use case?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 10.11.2023 16:48 schrieb Dominik ***@***.***>:
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.
Can you try to run tuya (local) and see if that works for your use case?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 10.11.2023 16:48 schrieb Dominik ***@***.***>:
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.
Can you try to run tuya (local) and see if that works for your use case?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
Am 10.11.2023 16:48 schrieb Dominik ***@***.***>:
Hi Frank,
I assume you are using the tuya_cloud module. I don't think that that will work without an internet connection. The tuya device needs to send the data to the cloud so that fhempy can receive that data from there. It's not working locally.
Can you try to run tuya (local) and see if that works for your use case?
