### ISSUE TITLE
address already in use bei Version 0.1.670

### ISSUE THREAD

**Issue by jowiemann** [fhempy/fhempy#206]
Hallo,

bekomme mal immer wieder folgenden Fehler.

2023-10-09 20:51:13,354 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/fhempy", line 162, in <module>
    fpb.run()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 755, in run
    loop.run_until_complete(async_main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/fhem/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 662, in async_main
    async with websockets.serve(
  File "/opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/server.py", line 1109, in __aenter__
    return await self
  File "/opt/fhem/.local/lib/python3.9/site-packages/websockets/legacy/server.py", line 1127, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 1494, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 15733): address already in use

Begleitet wird der Fehler durch das Erscheinen eines Fhem Device: [fhempy_peer_192_168_0_30]

Der Fehler: address already in use wird nur manchmal aufgehoben, wenn ich das neue Device lösche. 

Über eine Idee zur Lösung würde ich mich freuen.

**Comment by fhempy** [comment]
Da laufen scheinbar 2 fhempy Instanzen. Wie startest du fhempy? Stelle bitte sicher, dass es nur 1 Device vom Type fhempyServer gibt und du keinen Service (z.B. systemd) hast welches fhempy startet.

**Comment by jowiemann** [comment]
Hallo Dominik,

hatte ich auch erst vermutet. Hier meine Liste der Prozesse:

  PID TTY      STAT   TIME COMMAND
    1 ?        Ss     0:07 /sbin/init
    2 ?        S      0:00 [kthreadd]
    3 ?        I<     0:00 [rcu_gp]
    4 ?        I<     0:00 [rcu_par_gp]
    8 ?        I<     0:00 [mm_percpu_wq]
    9 ?        S      0:00 [rcu_tasks_rude_]
   10 ?        S      0:00 [rcu_tasks_trace]
   11 ?        S      0:00 [ksoftirqd/0]
   12 ?        I      0:01 [rcu_sched]
   13 ?        S      0:00 [migration/0]
   14 ?        S      0:00 [cpuhp/0]
   15 ?        S      0:00 [cpuhp/1]
   16 ?        S      0:00 [migration/1]
   17 ?        S      0:00 [ksoftirqd/1]
   20 ?        S      0:00 [cpuhp/2]
   21 ?        S      0:00 [migration/2]
   22 ?        S      0:00 [ksoftirqd/2]
   25 ?        S      0:00 [cpuhp/3]
   26 ?        S      0:00 [migration/3]
   27 ?        S      0:00 [ksoftirqd/3]
   30 ?        S      0:00 [kdevtmpfs]
   31 ?        I<     0:00 [netns]
   33 ?        I      0:00 [kworker/1:1-mm_percpu_wq]
   35 ?        S      0:00 [kauditd]
   37 ?        S      0:00 [khungtaskd]
   38 ?        S      0:00 [oom_reaper]
   39 ?        I<     0:00 [writeback]
   40 ?        S      0:00 [kcompactd0]
   58 ?        I<     0:00 [kblockd]
   59 ?        I<     0:00 [blkcg_punt_bio]
   60 ?        S      0:00 [watchdogd]
   61 ?        I<     0:00 [kworker/2:1H-kblockd]
   62 ?        I<     0:00 [rpciod]
   63 ?        I<     0:00 [kworker/u9:0-hci0]
   64 ?        I<     0:00 [xprtiod]
   65 ?        S      0:00 [kswapd0]
   66 ?        I<     0:00 [nfsiod]
   69 ?        I<     0:00 [iscsi_eh]
   70 ?        I<     0:00 [iscsi_destroy]
   71 ?        I<     0:00 [dwc_otg]
   73 ?        I<     0:00 [DWC Notificatio]
   75 ?        S<     0:00 [vchiq-slot/0]
   76 ?        S<     0:00 [vchiq-recy/0]
   77 ?        S<     0:00 [vchiq-sync/0]
   78 ?        I<     0:00 [zswap-shrink]
   84 ?        I<     0:00 [mmc_complete]
   86 ?        I<     0:00 [kworker/1:1H-kblockd]
   87 ?        S      0:00 [jbd2/mmcblk0p2-]
   88 ?        I<     0:00 [ext4-rsv-conver]
   90 ?        I<     0:00 [ipv6_addrconf]
   93 ?        I<     0:00 [kworker/3:1H-kblockd]
  107 ?        I<     0:01 [kworker/0:2H-mmc_complete]
  136 ?        S      0:00 [irq/199-usb-001]
  154 ?        Ss     0:01 /lib/systemd/systemd-udevd
  175 ?        S      0:00 [vchiq-keep/0]
  178 ?        S<     0:00 [SMIO]
  186 ?        I<     0:00 [mmal-vchiq]
  188 ?        I<     0:00 [mmal-vchiq]
  189 ?        I<     0:00 [mmal-vchiq]
  190 ?        I<     0:00 [mmal-vchiq]
  191 ?        I<     0:00 [mmal-vchiq]
  240 ?        I<     0:00 [cfg80211]
  250 ?        I<     0:00 [brcmf_wq/mmc1:0]
  252 ?        S      0:00 [brcmf_wdog/mmc1]
  453 ?        Ss     0:09 /lib/systemd/systemd-journald
  457 ?        Ssl    0:00 /lib/systemd/systemd-timesyncd
  462 ?        Ss     0:03 avahi-daemon: running [raspberrypi-2.local]
  463 ?        Ss     0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation --syslog-o
  472 ?        Ssl    0:00 /usr/bin/owftpd --foreground -c /etc/owfs.conf
  473 ?        Ssl    0:00 /usr/bin/owserver --foreground -c /etc/owfs.conf
  480 ?        Ssl    0:01 /usr/sbin/rsyslogd -n -iNONE
  489 ?        Ss     0:00 /lib/systemd/systemd-logind
  495 ?        Ss     0:00 /usr/sbin/thd --triggers /etc/triggerhappy/triggers.d/ --socket /run/thd.socket --user nobody --devic
  497 ?        Ss     0:00 /sbin/wpa_supplicant -u -s -O /run/wpa_supplicant
  515 ?        S      0:00 avahi-daemon: chroot helper
  548 ?        Ssl    0:00 /usr/libexec/owfs/owfs -c /etc/owfs.conf -c /etc/owfs.conf --allow_other /run/owfs
  556 ?        I<     0:00 [kworker/u9:1-hci0]
  557 ?        S      0:00 /usr/bin/hciattach /dev/serial1 bcm43xx 460800 noflow - b8:27:eb:2a:f2:99
  573 ?        Ssl    0:00 /usr/bin/owhttpd --foreground -c /etc/owfs.conf
  590 ?        Ss     0:00 /usr/libexec/bluetooth/bluetoothd
  597 ?        Ss     0:00 wpa_supplicant -B -c/etc/wpa_supplicant/wpa_supplicant.conf -iwlan0 -Dnl80211,wext
  610 ?        I<     0:00 [cryptd]
  702 ?        Ss     0:00 /sbin/dhcpcd -q -w
  704 ?        Rs     5:48 /usr/bin/perl fhem.pl fhem.cfg
  710 ?        Ss     0:00 /usr/sbin/nmbd --foreground --no-process-group
  715 ?        Ssl    0:03 npm start
  718 ?        I<     0:00 [cifsiod]
  719 ?        I<     0:00 [smb3decryptd]
  720 ?        I<     0:00 [cifsfileinfoput]
  721 ?        I<     0:00 [cifsoplockd]
  722 ?        I<     0:00 [cifs-dfscache]
  724 ?        S      0:00 [cifsd]
  743 ?        Ss     0:00 /lib/nut/upsmon
  745 ?        S      0:00 /lib/nut/upsmon
  747 ?        Ss     0:00 /usr/sbin/cron -f
  758 ?        Ss     0:00 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups
  764 tty1     Ss+    0:00 /sbin/agetty -o -p -- \u --noclear tty1 linux
  785 ?        SLsl   0:00 /usr/sbin/rngd -r /dev/hwrng
  837 ?        Ss     0:00 /usr/sbin/smbd --foreground --no-process-group
  847 ?        I      0:01 [kworker/u8:5-events_unbound]
  856 ?        Ss     0:00 sendmail: MTA: accepting connections
  859 ?        S      0:00 /usr/sbin/smbd --foreground --no-process-group
  860 ?        S      0:00 /usr/sbin/smbd --foreground --no-process-group
  862 ?        S      0:00 /usr/sbin/smbd --foreground --no-process-group
 1085 ?        Ss     0:00 sshd: ***@***.***
 1092 ?        Ss     0:00 /lib/systemd/systemd --user
 1093 ?        S      0:00 (sd-pam)
 1106 ?        S      0:00 sh -c node index.js
 1107 ?        Sl     0:14 node index.js
 1126 ?        Ss     0:00 /usr/lib/openssh/sftp-server
 1345 ?        Sl     0:06 node /usr/bin/alexa-fhem -c ./alexa-fhem.cfg
 1358 ?        Sl     0:04 python3 /opt/fhem/yowsup/yowsup-cli demos -c /opt/fhem/.config/yowsup/491632523214/config.json --yows
 1592 ?        S      0:01 /usr/bin/perl fhem.pl fhem.cfg
 1593 ?        S      0:00 /usr/bin/perl fhem.pl fhem.cfg
 1594 ?        S      0:00 /usr/bin/perl fhem.pl fhem.cfg
 1595 ?        S      0:02 /usr/bin/perl fhem.pl fhem.cfg
 1626 ?        S      0:00 /usr/bin/ssh -R 1234:127.0.0.1:33523 -oServerAliveInterval=90 -i /opt/fhem/.ssh/id_rsa -p 58824 fhem-
 1703 ?        Ss     0:00 sshd: ***@***.***
 1732 ?        Ss     0:00 /usr/lib/openssh/sftp-server
 3529 ?        I<     0:00 [kworker/3:0H]
 4885 ?        I      0:00 [kworker/0:1-mm_percpu_wq]
 5024 ?        I      0:00 [kworker/2:1-mm_percpu_wq]
 5398 ?        I      0:00 [kworker/3:1-events]
 5548 ?        I      0:00 [kworker/1:2-events_power_efficient]
 5846 ?        I      0:00 [kworker/u8:0-events_unbound]
 6122 ?        Ssl    0:04 /usr/bin/python3 /home/pi/.local/bin/fhempy
 6192 ?        I<     0:00 [kworker/1:2H]
 6902 ?        I      0:00 [kworker/0:0-events]
 6930 ?        I<     0:00 [kworker/2:2H]
 6958 ?        I<     0:00 [kworker/0:1H]
 6963 ?        I      0:00 [kworker/2:2-events_freezable]
 7424 ?        I      0:00 [kworker/3:0-mm_percpu_wq]
 8344 ?        I      0:00 [kworker/u8:1-events_unbound]
 8838 ?        I<     0:00 [kworker/1:0H]
 8882 ?        I      0:00 [kworker/2:0-events_power_efficient]
 8883 ?        I      0:00 [kworker/0:2-events]
 9015 ?        I<     0:00 [kworker/0:0H-kblockd]
 9138 ?        Ss     0:00 sshd: pi [priv]
 9319 ?        Ss     0:00 /lib/systemd/systemd --user
 9320 ?        S      0:00 (sd-pam)
 9338 ?        R      0:00 sshd: ***@***.***/0
 9339 pts/0    Ss     0:00 -bash
 9430 ?        I      0:00 [kworker/3:2-events]
 9576 ?        I      0:00 [kworker/1:0-mm_percpu_wq]
 9622 ?        I      0:00 [kworker/2:3-events]
 9716 ?        I<     0:00 [kworker/2:0H]
 9916 ?        I<     0:00 [kworker/3:2H-kblockd]
 9925 ?        I      0:00 [kworker/u8:2-brcmf_wq/mmc1:0001:1]
10529 pts/0    R+     0:00 ps -ax

Grüße Jörg

Von: Dominik
Gesendet: Montag, 9. Oktober 2023 21:11
An: fhempy/fhempy
Cc: jowiemann; Author
Betreff: Re: [fhempy/fhempy] address already in use bei Version 0.1.670 (Issue#206)

Da laufen scheinbar 2 fhempy Instanzen. Wie startest du fhempy? Stelle bitte sicher, dass es nur 1 Device vom Type fhempyServer gibt und du keinen Service (z.B. systemd) hast welches fhempy startet.

**Comment by fhempy** [comment]
Läuft das auf deinem System wo du auch FHEM laufen hast? Wenn ja, dann ist das hier der Fehler:
 6122 ?        Ssl    0:04 /usr/bin/python3 /home/pi/.local/bin/fhempy

In /home/pi sollte kein fhempy installiert sein.

**Comment by jowiemann** [comment]
Hallo Dominik,

danke für den Hinweis. Ich habe keine Erinnerung, warum und wie eine alte fhempy nach /home/pi/.local/bin gekommen ist. Aber das war das Problem. Danke Dir.

Herzliche Grüße

Jörg

Von: Dominik
Gesendet: Montag, 9. Oktober 2023 21:37
An: fhempy/fhempy
Cc: jowiemann; Author
Betreff: Re: [fhempy/fhempy] address already in use bei Version 0.1.670 (Issue#206)

Läuft das auf deinem System wo du auch FHEM laufen hast? Wenn ja, dann ist das hier der Fehler:
6122 ? Ssl 0:04 /usr/bin/python3 /home/pi/.local/bin/fhempy
In /home/pi sollte kein fhempy installiert sein.

**Comment by fhempy** [comment]
Gerne 👍
