### ISSUE TITLE
add more details for Skoda Connect

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#209]
is it possible to add more Details example:
--
Service is due in xxx days, it will be shown in the app

regards
simon

**Comment by jfmennedy** [comment]
I got these readings:
![image](https://github.com/fhempy/fhempy/assets/52569066/ee2eac4f-4188-4be9-b3fd-f93d63591ac9)

**Comment by tasisale** [comment]
Ok, I will use fhem and have a enyaq.
but will not see.
![Uploading IMG_3034.jpeg…]()

**Comment by jfmennedy** [comment]
so the data are not provided by the base lib (https://github.com/skodaconnect/skodaconnect)

**Comment by tasisale** [comment]
can you please help me to change fhem to https://github.com/skodaconnect/skodaconnect)

**Comment by jfmennedy** [comment]
You cannot change fhem to this library. The fhem module is based on this. But you can try the example code to see if the wanted informations are shown... To do this just clone the repository to your machine and run the example.py in a python environement.
