### ISSUE TITLE
not connecting at 04.11.2023 to skoda (VW)

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#215]
i have the problem that it will not connect to skoda afer the 04.11.2023, any problems known?

regard
simon

**Comment by kupfermuetze** [comment]
same for me (my last datapoint is from 2023-11-03T16:35:29), Under skoda-connect.com the data is updated.

**Comment by jfmennedy** [comment]
You need to update the base lib to 1.3.8 . I made already a pull request with the modification. still it is not implemented you need to update manually somewhere at your fhem path:

fhem\.local\lib\python3.9\site-packages\fhempy\lib\skodaconnect\mainfest.json

**Comment by tasisale** [comment]
how i make the update?

**Comment by jfmennedy** [comment]
You change the version number in manifset.json to 1.3.8
You find the file somewhere under the path 
`fhem\\.local\lib\python3.9\site-packages\fhempy\lib\skodaconnect\mainfest.json`

**Comment by tasisale** [comment]
ok, thx

**Comment by jfmennedy** [comment]
do not do an update of fhempy still this is not merged in the offical release, otherwise you need to modify again.

**Comment by kupfermuetze** [comment]
perfect, thanks for the instructions :-)

**Comment by fhempy** [comment]
PR merged. It should work with 0.1.671 out of the box :) Thx for reporting!
