### ISSUE TITLE
fhempy and Debian 12 (Bookworm)

### ISSUE THREAD

**Issue by Gisbert1** [fhempy/fhempy#218]
Hi Dominik,

it seems that fhempy does not work with Debian 12 (Bookworm). After a trial-and-error period, I have imported a Proxmox backup with Debian 11. Is there any idea or workaround which could be implemented e.g. by the user themselves?

Regards
Gisbert

**Comment by fhempy** [comment]
Hi,
Debian 12 uses Python 3.11 afaik. As I moved my development environment to 3.11 as well I think it should work. The only issue I had was that 3.11 required a venv to be created. Do you remember the error message?
I'm going to update my production environment to bookworm in the next weeks - usb stick is already flashed 😄

**Comment by Gisbert1** [comment]
Hi Dominik,
that's great and a few more weeks to wait is fine. I'm glad that you continue your project, I appreciate it very much.
The error message is documented in the Fhem forum: []()https://forum.fhem.de/index.php?topic=127441.msg1292459#msg1292459

**Comment by fhempy** [comment]
Yep, that's the error message I also received. Let's see how I can fix that one, it requires fhempy to be run within a Python virtual environment.

**Comment by fhempy** [comment]
Hi,
please do an update within FHEM and wait till fhempy is updated as well. It might take about 10 minutes to complete. Restart FHEM afterwards.

It automatically creates a virtual environment in /opt/fhem/.fhempy/fhempy_venv where fhempy is newly installed which should work for bookworm.

**Comment by jfmennedy** [comment]
Hi,

fhempy won´t start anymore after update. 
It tries to activate virtual environment:
```
Activating virtual environment...FHEM/bindings/python/bin/fhempy: line 34: source: .fhempy/fhempy_venv/bin/activate: is a directory
OK
No Python virtual environment available. Exit.
```
FHEM and fhempy running in a docker

**Comment by fhempy** [comment]
Could it be that it is not possible to create a virtual environment within a docker container?

Do you have a bookworm docker which you can use for testing?

**Comment by fhempy** [comment]
From a dependency point of view it wouldn't even make sense to have a venv within a docker. I'll check how I can drop venv creation within a docker.

**Comment by fhempy** [comment]
@jfmennedy can you please do an update in FHEM and try again? Thx!

**Comment by JorinL** [comment]
> @jfmennedy can you please do an update in FHEM and try again? Thx!

`root@homeland:/etc/portainerVolume/fhem/log# tail -F fhempy-2023-12-13.log
Running within a Docker container.
No Python virtual environment available. Exit.`

**Comment by jfmennedy** [comment]
Updated to 0.1.684 and now working for me in docker 👍

**Comment by fhempy** [comment]
> > @jfmennedy can you please do an update in FHEM and try again? Thx!
> 
> I tested:
> 
> * updated
> * restarted
> 
> `root@homeland:/etc/portainerVolume/fhem/log# tail -F fhempy-2023-12-13.log Running within a Docker container. No Python virtual environment available. Exit.`

Thanks for reporting! Please do another update within FHEM, it should work now.

**Comment by jfmennedy** [comment]
After Update in FHEM and restart I got this error and fhempy won´t start:
`
Running within a Docker container.
FHEM/bindings/python/bin/fhempy: line 52: syntax error in conditional expression
FHEM/bindings/python/bin/fhempy: line 53: syntax error near `then'
FHEM/bindings/python/bin/fhempy: line 53: `then'
`

**Comment by jfmennedy** [comment]
You need to add an space behind "$CONTAINER" == 0 in line 52 
/fhempy
`if [[ "$VIRTUAL_ENV" == "" && "$CONTAINER" == 0 ]]`
I modified at me and now its working

**Comment by Gisbert1** [comment]
Satire start:
This confirms my bias towards Linux and programming in general. When my son was still helping me with Linux, I jokingly said that we should insert a $ or an &, maybe a { is missing, but I never in my worst nightmares would have expected that spaces could be missing.
End satire
@jfmennedy, fhempy works now with Debian Bookworm - many thanks.
Many thanks also for Dominik for his great work. This is very much appreciated.

**Comment by JorinL** [comment]
Confirm -> works again :-)

Thank you!!

**Comment by fhempy** [comment]
Great to see that Debian 12 is now supported 👍 

Thanks everybody for testing and your feedback!
