### ISSUE TITLE
fhempy -> tibber

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#222]
is it possible to add  Tibber to fhempy?

can anyone help me add the mod -> https://github.com/Danielhiversen/pyTibber to fhempy?
is this possible?

regards
simon

**Comment by fhempy** [comment]
Which data do you want to be available in fhempy? I did a quick check with the DEMO_TOKEN and saw that a lot of data can be gathered.

**Comment by fhempy** [comment]
I just released a first version. Please test it and feel free to adapt or provide feedback.

**Comment by tasisale** [comment]
i will tested it, asap i get the update to new version running ;-)

regards
simon

**Comment by fhempy** [comment]
Please open a new issue if you have any issues with the tibber implementation.
