### ISSUE TITLE
Update esphome to at least 2023.8.0

### ISSUE THREAD

**Issue by sidey79** [fhempy/fhempy#228]
ESP home < 2023.8.0 uses pyyaml 6.0.0 which is broken since summer 2023 due to a update in cpython libs:

https://github.com/yaml/pyyaml/blob/c42fa3bff1eabdb64763bb1526d9ea1ccb708479/announcement.msg#L12

https://github.com/fhempy/fhempy/blob/0e7272fb299aaaabf9faf06135ca3a56bd7f1ec6/FHEM/bindings/python/fhempy/lib/esphome/manifest.json#L3

**Comment by fhempy** [comment]
Thank you for reporting!

The updated release should be ready in a few minutes.
