### ISSUE TITLE
Tested EQB3 with newest firmware 1.46 -> Works -> suggesting readme change.

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#230]
Hey there,
I just updated all my units to 1.46 -> works fine.
Pairing is needed and the units are then secure with changing PINs.

Added a changed Readme you can direclt start using.

Change is:

"Attention: Firmware from version 120 is recommended, successfully tested also with firmware 1.46 on 2023-12-07 15:14:48 (no newer firmware is currently known)"

[README.md](https://github.com/fhempy/fhempy/files/13601835/README.md)

**Comment by fhempy** [comment]
Thanks! I updated the readme with the instructions.
