### ISSUE TITLE
tuya_cloud: Readings werden nicht refreshed

### ISSUE THREAD

**Issue by derolf** [fhempy/fhempy#231]
Ich habe mehrere Currysmarter Jalousiensteuerungen, welche ich wunderbar mit FHEM ansteuern kann.

Allerdings werden die Readings nicht refreshed. Beispiel:

Von der Tuya-Cloud:

`2023-12-10 10:24:22	Report	Percentage	100%	device itself`

In FHEM:

`percent_control 0.0 2023-12-07 21:25:23`

Alle anderen Readings sind auch vom 7.12.

Das fhempy log sag folgendes relevantes dazu:

```
[2023-12-10 03:49:32,642] [tuya-openmq] Unexpected disconnection.7
2023-12-10 03:49:32,642 - ERROR    - tuya_iot: Unexpected disconnection.7
```

**Comment by fhempy** [comment]
Hast du schon tuya (nicht tuya_cloud) ausprobiert? Das läuft ganz lokal. Die tuya cloud ist nämlich nicht immer sehr zuverlässig.

Es gibt von tuya eine neue Library (https://github.com/tuya/tuya-device-sharing-sdk) die ich dann zukünftig nutzen werde, vielleicht klappt es mit der dann besser.

**Comment by Sequenzial** [comment]
Hatte das Problem auch mit tuya_cloud. Allerdings lag es bei mir daran, dass in Fhem, in den automatisch erzeugten Devices, kein "IODev" definiert war. 
Komischerweise hatte er initial beim erstellen einmal Werte bekommen.
Bei mir hat das setzen des IODev genügt, dann kamen die Werte.

**Comment by fhempy** [comment]
Hi,
könnt ihr bitte tuya_smartlife ausprobieren? Vielleicht klappt es damit besser, das ist zumindest die letzte Library die Tuya selbst veröffentlicht hat.

**Comment by normen** [comment]
Ich habe dasselbe Problem. Nur wenn ich fhempy neu starte oder das tuya_smartlife Gerät neu einrichte werden die Daten einmal ausgelesen...
