### ISSUE TITLE
Since last update (I updated on 13.12.23) -> "fhempy/fhempy_venv/bin/activate: No such file or directory"

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#232]
Good morning ;-)

After the update I made this morning, I receive this error in the fhempy log:

`Activating virtual environment...FHEM/bindings/python/bin/fhempy: line 34: .fhempy/fhempy_venv/bin/activate: No such file or directory
OK
No Python virtual environment available. Exit.
`

First there was also the info: "python3-venv" was missing.
Added this to my fhem container setup.

Now only the info above is given.

EQ3BT Control is working nevertheless.
Only the fhempy in the container is not working/starting/or visible correct (127.0.1.1:15733 fhempy) and (Pythonbinding_0 fhempyServer 0)

![image](https://github.com/fhempy/fhempy/assets/33031729/f4391c1a-543f-4691-b3f4-e73ddff1e6c0)

Versions Peer: 0.1.684 
![image](https://github.com/fhempy/fhempy/assets/33031729/d74b60b2-c01e-4fb4-8013-fcd2dda943d1)

Any idea? :-)
Thanks!

**Comment by fhempy** [comment]
Hi,
can you please try to do a
`python3 -m venv .fhempy/fhempy_venv`
in the $HOME directory of the FHEM user (e.g. /opt/fhem). It seems that the command is not working in your environment.

**Comment by fhempy** [comment]
Could it be that you are running FHEM within docker? If so, please see #218

**Comment by JorinL** [comment]
That is exactly the case.

Checking it.

**Comment by JorinL** [comment]
Changeging to #218
