### ISSUE TITLE
Fhempy Server not starting anymore

### ISSUE THREAD

**Issue by herble-coc** [fhempy/fhempy#235]
Hi, Since latest update fhempy server didn't start anymore.
fhempy_local: Can't connect to ws:127.0.0.1:15733: Operation now in progress
fhempy_local: Can't connect to ws:127.0.0.1:15733: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
 BindingsIo (fhempy_local): ERROR during connection setup: 127.0.0.1: Verbindungsaufbau abgelehnt (111)

Any idea how to fix?

**Comment by tasisale** [comment]
i have the same problem.
please help

**Comment by fhempy** [comment]
Please post content from the fhempy log file.

**Comment by tasisale** [comment]
-- Logs begin at Wed 2023-05-24 21:21:54 CEST. --
Dez 15 22:19:56 srvfhem systemd[1]: Started fhempy.
Dez 15 22:19:56 srvfhem systemd[54348]: fhempy.service: Failed to determine user credentials: No such process
Dez 15 22:19:56 srvfhem systemd[54348]: fhempy.service: Failed at step USER spawning /home/pi/.fhempy/fhempy_venv/bin/fhempy: No such process
Dez 15 22:19:56 srvfhem systemd[1]: fhempy.service: Main process exited, code=exited, status=217/USER
Dez 15 22:19:56 srvfhem systemd[1]: fhempy.service: Failed with result 'exit-code'.
Dez 15 22:19:56 srvfhem systemd[1]: fhempy.service: Scheduled restart job, restart counter is at 5.
Dez 15 22:19:56 srvfhem systemd[1]: Stopped fhempy.
Dez 15 22:19:56 srvfhem systemd[1]: fhempy.service: Start request repeated too quickly.
Dez 15 22:19:56 srvfhem systemd[1]: fhempy.service: Failed with result 'exit-code'.
Dez 15 22:19:56 srvfhem systemd[1]: Failed to start fhempy.

**Comment by fhempy** [comment]
It seems you are running fhempy on a peer. Can you please let me know how you updated it?
The issue is, that the virtual environment is missing.

Try
python -m venv .fhempy/fhempy_venv
source .fhempy/fhempy_venv/bin/activate
pip3 install fhempy

**Comment by herble-coc** [comment]
Unfortunately it didn'twork for me. 
In fhempy log 
Activating virtual environment...FHEM/bindings/python/bin/fhempy: Zeile 47: .fhempy/fhempy_venv/bin/activate: Datei oder Verzeichnis nicht gefunden
OK
No Python virtual environment available. Exit.

(fhempy_venv) 1:~$ python -m venv .fhempy/fhempy_venv
(fhempy_venv) 1:~$ source .fhempy/fhempy_venv/bin/activate
(fhempy_venv) 1:~$ pip3 install fhempy
Requirement already satisfied: fhempy in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (0.1.684)
Requirement already satisfied: aiohttp==3.8.6 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp[speedups]==3.8.6->fhempy) (3.8.6)
Requirement already satisfied: async-upnp-client==0.31.2 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (0.31.2)
Requirement already satisfied: importlib_metadata==6.1.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (6.1.0)
Requirement already satisfied: markdown2==2.4.10 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (2.4.10)
Requirement already satisfied: packaging==23.2 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (23.2)
Requirement already satisfied: pycryptodomex==3.18.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (3.18.0)
Requirement already satisfied: requests==2.31.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (2.31.0)
Requirement already satisfied: websockets==11.0.3 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (11.0.3)
Requirement already satisfied: zeroconf==0.64.1 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from fhempy) (0.64.1)
Requirement already satisfied: attrs>=17.3.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (3.3.2)
Requirement already satisfied: multidict<7.0,>=4.5 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (1.9.4)
Requirement already satisfied: frozenlist>=1.1.1 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (1.4.1)
Requirement already satisfied: aiosignal>=1.1.2 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp==3.8.6->aiohttp[speedups]==3.8.6->fhempy) (1.3.1)
Requirement already satisfied: aiodns in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp[speedups]==3.8.6->fhempy) (3.1.1)
Requirement already satisfied: Brotli in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiohttp[speedups]==3.8.6->fhempy) (1.1.0)
Requirement already satisfied: voluptuous>=0.12.1 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from async-upnp-client==0.31.2->fhempy) (0.14.1)
Requirement already satisfied: python-didl-lite~=1.3.2 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from async-upnp-client==0.31.2->fhempy) (1.3.2)
Requirement already satisfied: defusedxml>=0.6.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from async-upnp-client==0.31.2->fhempy) (0.7.1)
Requirement already satisfied: zipp>=0.5 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from importlib_metadata==6.1.0->fhempy) (3.17.0)
Requirement already satisfied: idna<4,>=2.5 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from requests==2.31.0->fhempy) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from requests==2.31.0->fhempy) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from requests==2.31.0->fhempy) (2023.11.17)
Requirement already satisfied: ifaddr>=0.1.7 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from zeroconf==0.64.1->fhempy) (0.2.0)
Requirement already satisfied: pycares>=4.0.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from aiodns->aiohttp[speedups]==3.8.6->fhempy) (4.4.0)
Requirement already satisfied: cffi>=1.5.0 in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from pycares>=4.0.0->aiodns->aiohttp[speedups]==3.8.6->fhempy) (1.16.0)
Requirement already satisfied: pycparser in ./.fhempy/fhempy_venv/lib/python3.10/site-packages (from cffi>=1.5.0->pycares>=4.0.0->aiodns->aiohttp[speedups]==3.8.6->fhempy) (2.21)

**Comment by fhempy** [comment]
Are you running fhempy on the same machine as FHEM is running?

**Comment by herble-coc** [comment]
Yes. Same machine. A NUC

**Comment by fhempy** [comment]
You shouldn't run fhempy from systemd in that case. Please remove the systemd fhempy service.

Please delete /opt/fhem/.fhempy/fhempy_venv and execute `sudo apt install python3-venv`. After that restart FHEM.

**Comment by herble-coc** [comment]
It fixed it. Anyway what is strange that this setup works for almost a year now. However, many thanks for support and patience

**Comment by fhempy** [comment]
I think the missing python3-vemv package was the issue. I added bookworm support the last days which requires venv. Looks like I should add a check if the package is installed.

Thanks for reporting!

@tasisale does that work for you as well?

**Comment by tasisale** [comment]
no, sorry i have the error again.

**Comment by tasisale** [comment]
here is the detail for python from my install.
--
sudo apt install python3-venv
[sudo] Passwort für fhemadmin:
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
python3-venv ist schon die neueste Version (3.8.2-0ubuntu2).
0 aktualisiert, 0 neu installiert, 0 zu entfernen und 0 nicht aktualisiert.
fhemadmin@srvfhem:~$ python3
Python 3.8.10 

regards
simon

**Comment by tasisale** [comment]
ok, i have delete the folder "/opt/fhem/.fhempy/fhempy_venv" again and restart the nuc.
Now it installed the Update -> 0.1.686 and its green again.
Now i will hope my skoda Connection will go.

**Comment by fhempy** [comment]
Please reopen if fhempy doesn't work. Please create a new issue if the skodaconnection isn't working. Thx!
