### ISSUE TITLE
can not update from 0.1.689 -> 0.1.693

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#274]
i klick on Update, will do anything and i come back to the old version, but why?
![fhempy_update](https://github.com/fhempy/fhempy/assets/78930595/8164f3fb-3711-490b-b65d-4e242c3a8db8)
--
![fhempy_update_start](https://github.com/fhempy/fhempy/assets/78930595/7b3f2bc0-b5d3-438b-89ec-aad42cfecc1f)

--
![fhempy_update_start2](https://github.com/fhempy/fhempy/assets/78930595/72be6997-f6c3-41d2-8bd3-f0185bbc90f1)
--
![fhempy_status](https://github.com/fhempy/fhempy/assets/78930595/0a31e8c8-0e7a-42df-b675-6cac4a5cb1a2)

can anyone help we, thx.

**Comment by tasisale** [comment]
after python3.8.10 - Update to 3.11.7 an make it as default.
now all works again.

**Comment by fhempy** [comment]
Oh, you have still been on 3.8.10? Actually 3.8 wasn't supported by fhempy any more, as it relies on 3.9 or higher.
I'm going to close the issue as it works for you.
