### ISSUE TITLE
meross_integration failure - No Connection to Meross Devices

### ISSUE THREAD

**Issue by SiggiBS** [fhempy/fhempy#278]
No Connection to Meross Devices with fhempy 0.1.693 /see log-entries below
Fhempy 0.1.670 for example still works

2023-12-27 15:31:57,078 - ERROR    - meross_integration: Exception raised by task: <Task finished name='Task-89' coro=<FhemModule._run_coro() done, defined at /opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py:216> exception=TypeError("MerossHttpClient.async_from_user_password() missing 1 required positional argument: 'api_base_url'")>
Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py", line 224, in _handle_task_result
    task.result()
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/generic.py", line 218, in _run_coro
    await coro
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.10/site-packages/fhempy/lib/meross/meross_setup.py", line 27, in run_setup
    http_api_client = await MerossHttpClient.async_from_user_password(

**Comment by SiggiBS** [comment]
FYI - From Meross - Support I get the following information via email yesterday. (But till tody Fhempy 0.1.670 for example still works)

_Dear user,
Thank you for your continued support and trust. According to our terms of service, we would like to provide you with a notification and guidance regarding the discontinuation of our old services and the upgrade to our new services.
1. Reason for service discontinuation and upgrade:
This update aims to enhance user experience, improve data security, and ensure our services can adapt to the evolving technological environment.
2. Service discontinuation and upgrade actions:
We plan to discontinue certain cloud interfaces at 2024-01-01 Pacific Time and only maintain and support the upgraded versions of the interfaces.
3. Scope of impact:
This discontinuation will affect certain functionalities of the old app versions, including (login).
4. Actions required:
1) To ensure you can continue using our services smoothly, please upgrade to the latest version of the app before the interface discontinuation date. Any app version older than Android V2.26.0 or iOS V2.22.0 will no longer allow login and access. The new app version will include performance optimizations, security improvements, and exciting new features that you will surely enjoy.
2) If you are already using the latest version of the app, no further action is needed.
3) If you are using third-party platforms not authorized by Meross to manage our devices, we cannot guarantee their compatibility with our new cloud interfaces or the security of your devices and data. Please switch back to our official services, as stated in our terms of service, to ensure proper functionality.
5. Upgrade steps:
Please go to the application store (App Store or Google Play) to update our app to the latest version. If you have enabled automatic updates, no manual action is required as the system will handle the upgrade at the appropriate time.
6. Technical support:
If you encounter any issues during the upgrade process or have any feedback regarding the new version, please feel free to contact our technical support team. You can reach us at [support@meross.com](mailto:support@meross.com).
We understand that this may cause some inconvenience, but we firmly believe that this update will bring you a better user experience and enhanced data security. Thank you for your understanding and cooperation.
Wishing you a delightful experience!
[Meross Cloud Team]_

**Comment by fhempy** [comment]
Hi,

this issue was caused by the merossiot library update which changed the API. A fix is on the way and will be available in 30min => https://github.com/fhempy/fhempy/commit/fb7be3707d582da6ebc72411a6f1819228bb0893

Please test afterwards and report back. Thx!

**Comment by SiggiBS** [comment]
Hi,
Works perfect.  Thank you for the ultra fast fix!!!
