### ISSUE TITLE
esphome complains about pillow

### ISSUE THREAD

**Issue by Heiner1967** [fhempy/fhempy#293]
Hi, 
since upgarde ESP home request upgarde of pillow installation to 10.1.0 which i did and get confirmed to be installed.
ESPhome however does not recognise it and complains that i still need to update pillow.

As well opended as espHome issue, but i seem to be alone in that forum with this problem

**Comment by fhempy** [comment]
Can you please provide the log? Does that happen during the installation?

**Comment by Heiner1967** [comment]
No, installation went well and the command
pip3 show pillow
show the correctly installed Version 10.1.0

If I then go to esphome and start compiling my code....
it state in the beginning the latest ESP Version 2023 12 5     ( correct)
and then complains about pillow as soon as ESPhome reads the codeline for a Display I use ( which was fine before)
and it says I shall update pillow to 10.1.0.

When I edit my code, the display rows are red underligned and hovering with the mouse over it, a pop-up window is telling me the same.

On the ESPHOME page it mentioned that with the last release pillow shall be updated.

I opened a ticket in ESPHOME forum as well here: https://github.com/esphome/issues/issues/5347

**Comment by Heiner1967** [comment]
esphome refers to hear.
Another one https://github.com/esphome/issues/issues/5077 gave a idea, i struggle however to verify as i do not find installationfolder of esphome under debian as installed by fhempy

**Comment by Heiner1967** [comment]
Here the ESPHOME log:

> INFO ESPHome 2023.12.5
> INFO Reading configuration esphome_config/sprinkler.yaml...
> Failed config
> 
> display.ili9xxx: [source esphome_config/sprinkler.yaml:50]
>   
>   Please update your pillow installation to 10.1.0. (pip install "pillow==10.1.0").
>   platform: ili9xxx
>   model: ILI9341
>   dc_pin: 27
>   reset_pin: 33
>   rotation: 90
>   cs_pin: 25

pip 3 show pillow showed correct Version.

> pi@rpi:/opt/fhem/FHEM $ pip3 show pillow
> Name: Pillow
> Version: 10.1.0
> Summary: Python Imaging Library (Fork)
> Home-page: https://python-pillow.org
> Author: Jeffrey A. Clark (Alex)
> Author-email: aclark@aclark.net
> License: HPND
> Location: /home/pi/.local/lib/python3.9/site-packages
> Requires:
> Required-by:

I found the problem:
installing again with Sudo showed the correct installation and replacement of the old Version.

Stupid me, sorry for opening the issue  -hopefully the solution helps others
