### ISSUE TITLE
[Function Request] Peer setup -> Bind to IP

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#295]
Hey there :-)
For running several applications on my home Server - it is needed to have 2 IP addresses.
Because some apps need exactly "that one port" and you have more than one app also want to have exactly this port.

So it would be really great to bind the peer to an IP and not having em on 0.0.0.0 because that leads currently to two instances where you can update and restart - but the communication is only working really good with one of them.

![image](https://github.com/fhempy/fhempy/assets/33031729/e0e29bbf-e323-4c56-890e-fbf6e42f8e23)
Those are exactly the same instance but it is connected to two seperate ips.

:-)

If that would not be that big thing -> It would be very nice!

Thanks

**Comment by fhempy** [comment]
Hi,
can you please try to run fhempy with -i192.168.0.x (the IP address you want to be used)? This option defines the IP address which will be used in zeroconf to advertise the fhempy service.

**Comment by JorinL** [comment]
Hey ;-)
Thanks for the help.

I run it as a services.
Can I set it in the service file or in a config file?

**Comment by fhempy** [comment]
If you run it as a service you just need to add the option in the fhempy.service file.

**Comment by JorinL** [comment]
Hey there :-)

tried:
`# Source: https://github.com/fhempy/fhempy

# ATTENTION
# This is an example, please verify your directories and user
#
# Copy this file to /etc/systemd/system/fhempy.service
# Start service with "sudo systemd start fhempy"
#

[Unit]
Description=fhempy
Wants=network.target
After=network.target

[Service]
User=jorin
Group=jorin
WorkingDirectory=/home/jorin/
ExecStart=/home/jorin/.local/bin/fhempy -i192.168.0.8
Restart=always

[Install]
WantedBy=multi-user.target
`

get:
`/etc/systemd/system$ sudo netstat -tulpen | grep 15733
tcp        0      0 0.0.0.0:15733           0.0.0.0:*               LISTEN      1000       80237984   1892016/python3
`

**Comment by fhempy** [comment]
Sorry, I got it wrong.

I added a new parameter `-b` where you can specify the IP address to bind to.
Just update to the latest version and use `-b` instead of `-i`. The updated version is going to be available in 15min.

**Comment by JorinL** [comment]
Hey there, cool thanks!

So like this?

Hey there :-)

tried:
```# Source: https://github.com/fhempy/fhempy

# ATTENTION
# This is an example, please verify your directories and user
#
# Copy this file to /etc/systemd/system/fhempy.service
# Start service with "sudo systemd start fhempy"
#

[Unit]
Description=fhempy
Wants=network.target
After=network.target

[Service]
User=jorin
Group=jorin
WorkingDirectory=/home/jorin/
ExecStart=/home/jorin/.local/bin/fhempy -b192.168.0.8
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by fhempy** [comment]
Thanks for testing! Fix will be available in a few minutes.

**Comment by JorinL** [comment]
--bind 192.168.0.8 works

-b 192.168.0.8 seems not.

For me that is okay ^^  :-)

Thanks

**Comment by fhempy** [comment]
It only works if you remove the blank between b and 1. I don't know why 😕 

Nevertheless, great to see that it works! Thank you for your feedback!

**Comment by JorinL** [comment]
Thanks for fixing :-)
Anytime agin.
