### ISSUE TITLE
Skoda Connect - can not set climatisation_target_temperature

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#308]
i can not set the "climatisation_target_temperature", it will do nothing when i set for example to 22.
Can you Help, or is this set not possible from VM/SKODA?

regards
simon

**Comment by tasisale** [comment]
NEWS, it is not possible to set to 22.5 oder any xx.x, the error shows.
--
`Failed to execute function Set: Traceback (most recent call last):
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 385, in handle_function
    ret = await self.execute_function(hash, fhem_reply_done, nmInstance)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/fhem_pythonbinding.py", line 484, in execute_function
    ret = await asyncio.wait_for(
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/tasks.py", line 489, in wait_for
    return fut.result()
           ^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/generic.py", line 208, in Set
    return await utils.handle_set(self._conf_set, self, hash, args, argsh)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 327, in handle_set
    final_params[param] = convert2format(
                          ^^^^^^^^^^^^^^^
  File "/opt/fhem/.fhempy/fhempy_venv/lib/python3.11/site-packages/fhempy/lib/utils.py", line 235, in convert2format
    return int(value)
           ^^^^^^^^^^
ValueError: invalid literal for int() with base 10: '22.5'`

**Comment by fhempy** [comment]
Test with the latest version, please. It will be available in 10min.

**Comment by tasisale** [comment]
the x.5 steps now works.
but it woll net send to the skoda server.
i send -> `set my_skoda climatisation_target_temperature 22.5` and press enter, but nothing is do.

**Comment by fhempy** [comment]
Looks like that isn't supported via API:
https://github.com/skodaconnect/skodaconnect/blob/main/skodaconnect/vehicle.py#L655

I'm going to close the issue as it can't be implemented right now.

**Comment by tasisale** [comment]
> Looks like that isn't supported via API: https://github.com/skodaconnect/skodaconnect/blob/main/skodaconnect/vehicle.py#L655
> 
> I'm going to close the issue as it can't be implemented right now.

The set_climater service should support this. That being set I recall some discussion on Discord about issues with it.
service: skodaconnect.set_climater
data:
  temp: 22
