### ISSUE TITLE
Installation of fhempy peer on Pi Zero W -> VERY Very Slow and breaks sometimes

### ISSUE THREAD

**Issue by JorinL** [fhempy/fhempy#331]
Hey there,

since the newest update my zero W seems to do not like the fhempy stuff anymore :-)
Is there some heavy change?

![image](https://github.com/fhempy/fhempy/assets/33031729/001d8644-c44b-4358-b701-7b157c3bb873)

It takes ages.
And stopped working totally yesterday - so i reinstalled completely.

*Edit -> still standing on

"Building wheels for collected packages: zeroconf
  Building wheel for zeroconf (PEP 517) ... |"

for 21 minutes O_o
System = fresh Raspian from Rapsian Imager.

**Comment by fhempy** [comment]
Looks like the zeroconf wheel package is missing for Pi Zero. If the package is missing, it's getting built which might take some hours. Please test again in a few days, sometimes it takes some time until the packages are provided.

**Comment by JorinL** [comment]
Mhh...
![image](https://github.com/fhempy/fhempy/assets/33031729/474f1050-f577-4a96-b14d-4b0b77ad9441)

**Comment by fhempy** [comment]
Can you please try
sudo -u fhem bash
cd
source .fhempy/fhempy_venv/bin/activate
pip3 install zeroconf

Please post the output of the commands.

**Comment by JorinL** [comment]
Waited now a day for:

`Building wheels for collected packages: zeroconf
  Building wheel for zeroconf (PEP 517) ... done`
  
:-D

`pi@Zerow:~ $ systemctl status fhempy
● fhempy.service - fhempy
     Loaded: loaded (/etc/systemd/system/fhempy.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2024-02-18 19:59:03 GMT; 44s ago
   Main PID: 4708 (fhempy)
      Tasks: 4 (limit: 414)
        CPU: 35.102s
     CGroup: /system.slice/fhempy.service
             ├─4708 /home/pi/.fhempy/fhempy_venv/bin/python3 /home/pi/.fhempy/fhempy_venv/bin/fhempy
             └─4717 /home/pi/.fhempy/fhempy_venv/bin/python3 -m pip install --quiet construct==2.10.70 --upgrade
`

So would like to not kill it again yet.

But will check on that idea if needed in the future.

**Comment by JorinL** [comment]
Closed due - worked out after long waiting ;-)

**Comment by JorinL** [comment]
> Can you please try
> sudo -u fhem bash
> cd
> source .fhempy/fhempy_venv/bin/activate
> pip3 install zeroconf
> 
> Please post the output of the commands.


Now I did it ;-)

```

pi@Zerow:~ $ source .fhempy/fhempy_venv/bin/activate
(fhempy_venv) pi@Zerow:~ $ pip3 install zeroconf
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: zeroconf in ./.fhempy/fhempy_venv/lib/python3.9/site-packages (0.130.0)
Requirement already satisfied: async-timeout>=3.0.0 in ./.fhempy/fhempy_venv/lib/python3.9/site-packages (from zeroconf) (4.0.3)
Requirement already satisfied: ifaddr>=0.1.7 in ./.fhempy/fhempy_venv/lib/python3.9/site-packages (from zeroconf) (0.2.0)

```
