### ISSUE TITLE
attr fhempy device_readings

### ISSUE THREAD

**Issue by fhempy** [fhempy/fhempy#339]
The attribute device_reading for RCT accepts only comma separated arguments like battery.bms_sn,battery.bms_power_version.
The structure: 
{\
battery.bms_sn,\
battery.bms_power_version\
}
does not work or I could not figure out the correct syntax.
Could you please add the option for multi line input or give a hint for the correct syntax.
Thank you
Chris

_Originally posted by @yalgoo in https://github.com/fhempy/fhempy/discussions/334_

**Comment by fhempy** [comment]
You just need to use:
`battery.bms_sn,battery.bms_power_version`
in the device_readings attribute. You don't need to provide it in JSON format.

**Comment by fhempy** [comment]
Please reopen if it doesn't work for you.

**Comment by yalgoo** [comment]
Thanks - I fixed it with an excel hack to read the parameters from rctclient and format them into JSON format. 
[RCT-Power-Parameter_R2.xlsx](https://github.com/fhempy/fhempy/files/14320048/RCT-Power-Parameter_R2.xlsx)
![Power query](https://github.com/fhempy/fhempy/assets/135171995/afb0146f-ee05-4197-b743-8743fc32ae6e)
