### ISSUE TITLE
Meross: Values of Power Consumption

### ISSUE THREAD

**Issue by Mike1969n** [fhempy/fhempy#350]
Is it possible to integrate the values of power consumption, that are shown in the app, as readings in FHEM?

**Comment by fhempy** [comment]
I just published a new version which adds power, voltage, current readings. Would be great if you could test it and let me know if it works. Thx!

**Comment by Mike1969n** [comment]
I receive values in the 3 readings. I will proof the values with the Meross-app. Thank you!
