### ISSUE TITLE
Re-Installation - EnvironmentError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by StefanGitter** [fhempy/fhempy#376]
Hi,

After reverting to a backup of my /opt/fhem/ folder, fhempy_local was disconnected with errors in fhem Log:
```
2024.03.26 10:38:46 1: fhempy_local: Can't connect to ws:127.0.0.1:15733: Illegal seek
2024.03.26 10:38:46 1: fhempy_local: Can't connect to ws:127.0.0.1:15733: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2024.03.26 10:38:46 1: BindingsIo (fhempy_local): ERROR during connection setup: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
```

and in fhempy-2024-03-26.log:
```
2024-03-26 13:26:33,224 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/fhempy", line 139, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2024-03-26 13:26:33,225 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2024-03-26 13:28:20,831 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
ERROR: Could not install packages due to an EnvironmentError: [Errno 13] Keine Berechtigung: '/root/.local'
Check the permissions.
```

I found out that I could install fhempy and all the dependencies for tuya as root user, which made fhempy and tuya run again in FHEM:
```
pip3 install fhempy
pip3 install tuya-iot-py-sdk==0.6.6
pip3 install tuya-connector-python==0.1.2
pip3 install tinytuya
pip3 install git+https://github.com/fhempy/aiotinytuya#aiotinytuya==1.12.3
```

However, in https://github.com/fhempy/fhempy/issues/188 I saw that the correct directories should be /opt/fhem/.local/lib and /opt/fhem/.local/bin, which already exist on my bullseye raspi with owner set to `fhem.dialout`.

How can I fix my fhempy installation so that it accesses /opt/fhem/.local instead of trying to access /root/.local which fails due to permissions, so that it can update automatically again?

**Comment by fhempy** [comment]
Please delete fhempy completely and do a fresh install.
```
sudo pip3 uninstall fhempy
sudo -u fhem bash
pip3 uninstall fhempy
```
Restart the fhempy server afterwards to trigger a new installation.

**Comment by StefanGitter** [comment]
Thank you for this idea! I will try this next time in such a situation.
This time, I managed to restore a working backup of the whole SD card partition. There the fhempy update works.

**Comment by StefanGitter** [comment]
Thank you for this idea! I will try this next time in such a situation.
This time, I managed to restore a working backup of the whole SD card partition. There the fhempy update works.
