### ISSUE TITLE
Infos zum Modul core

### ISSUE THREAD

**Issue by sidey79** [fhempy/fhempy#392]
Ich bräuchte ein paar Infos zum Modul core.

Aktuell erzeuge ich ja für jedes Modul, welches Abhängigkeiten hat ein eigenes Docker Image, da einige Module unterschiedliche Anforderungen an Abhängigkeiten hatten.

Ich bekam nun einen Hinweis und bemerkte, dass ich keine Images erzeuge, wenn in manifest.json keine Abhängigkeit steht.
Das bin ich beim Anpassen.
Dabei ist mir aufgefallen, dass das Modul core selbst kein manifest.json hat dafür aber noch ein Submodul.

Da es keine Readme gibt würde ich gerne wissen, ob es dieses Modul braucht oder ob ich es weiterhin ignorieren kann.

https://github.com/fhem/fhempy-docker/pull/170

**Comment by fhempy** [comment]
Hi,

core musst du nicht berücksichtigen. Core wird von fhempy "main" verwendet und die Abhängigkeiten sind bereits alle in pyproject.toml in den [tool.poetry.dependencies] abgedeckt.
