### ISSUE TITLE
tibber will not load all actual data

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#398]
Not all Data will load.
![fehler_tibber](https://github.com/fhempy/fhempy/assets/78930595/d5daca26-e933-4f8c-8fb5-5beb2534a542)

I have done a reboot of Fhem and a reboot ot he pc, any the same error, can ypu please check.

regards
simon

**Comment by dreichelt14** [comment]
Hi Simon,

in my tibber account the price changes at the beginning of a new hour. Therefore, all data except the rt_* data get updated only every new hour. Masterdata e.g. has_production get load only once at FHEM startup. Do you miss any other data or have any other data that needs to be updated more frequently?

bests
Dirk

**Comment by fhempy** [comment]
Thanks for the fix! It is already available in the last release.

**Comment by dreichelt14** [comment]
@fhempy  dependabot[bot] changed it the dependency back to 0.28.2 ! This breaks again parts of the code.

**Comment by fhempy** [comment]
Thx for reporting! I have fixed the version.
