### ISSUE TITLE
Error - Datei oder Verzeichnis nicht gefunden

### ISSUE THREAD

**Issue by tasisale** [fhempy/fhempy#423]
chmod: Zugriff auf 'FHEM/bindings/python/bin/start_fhempy.py' nicht möglich: Datei oder Verzeichnis nicht gefunden
FHEM/bindings/python/bin/fhempy: Zeile 70: /home/fhem/FHEM/bindings/python/bin/start_fhempy.py: Datei oder Verzeichnis nicht gefunden
Activating virtual environment...OK

what can i do, is a new installed Ubuntu on Intel NUC with python 3.12.3

regards
simon

**Comment by fhempy** [comment]
Are you running fhempy on a peer or on the same host as FHEM is running on? Looks like the same host but you have forgotten to do an update (within FHEM) to install the file.

**Comment by tasisale** [comment]
hi its running on the same host as FHEM.
have done all Updates, waht can i do?

**Comment by stephan-loescher** [comment]
Hi!
I had the same issue.
I think the root cause of this error is the relative path in fhempy script here: FHEM/bindings/python/bin/start_fhempy.py in lines 67 and 70.
My FHEM installation is in /opt/fhem/fhem and HOME of my fhem user is /home/fhem.
I made this workaround:
ln -s /opt/fhem/fhem/FHEM /home/fhem/
BR, Stephan.

**Comment by tasisale** [comment]
> Hi! I had the same issue. I think the root cause of this error is the relative path in fhempy script here: FHEM/bindings/python/bin/start_fhempy.py in lines 67 and 70. My FHEM installation is in /opt/fhem/fhem and HOME of my fhem user is /home/fhem. I made this workaround: ln -s /opt/fhem/fhem/FHEM /home/fhem/ BR, Stephan.

thx, have done the same, but now i have a new error show:
--
`2024-05-07 22:09:11,118 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/home/fhem/FHEM/bindings/python/bin/start_fhempy.py", line 141, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2024-05-07 22:09:11,125 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2024-05-07 22:09:11,161 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: /home/fhem/.fhempy/fhempy_venv/bin/python3: No module named pip
2024-05-07 22:09:11,161 - ERROR    - __main__: Failed to install fhempy, exit now...`

**Comment by stephan-loescher** [comment]
Do you have installed "pip"?

**Comment by tasisale** [comment]
> Do you have installed "pip"?

YES, PIP and PIP3 are installed.
But the Same Error, ahhhh

**Comment by tasisale** [comment]
i get the error:
--
`Traceback (most recent call last):
  File "/home/fhem/FHEM/bindings/python/bin/start_fhempy.py", line 141, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'
2024-05-14 15:02:20,123 - INFO     - __main__: Attempting install of fhempy>=0.1.462
2024-05-14 15:02:20,158 - ERROR    - __main__: Unable to install package fhempy>=0.1.462: /home/fhem/.fhempy/fhempy_venv/bin/python3: No module named pip
2024-05-14 15:02:20,158 - ERROR    - __main__: Failed to install fhempy, exit now...`

**Comment by tasisale** [comment]
and, pip is installed
--
`:~$ pip --version
pip 24.0 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)`

**Comment by fhempy** [comment]
pip is required in your venv, not the globale installation.
Please check if you have pip in home/fhem/.fhempy/fhempy_venv/bin/

You might also try to
rm -rf /home/fhem/.fhempy/fhempy_venv
python3 -m venv /home/fhem/.fhempy/fhempy_venv

**Comment by tasisale** [comment]
your are the BEST, thx.
Now it works.

regards
simon
