### ISSUE TITLE
Use latest ring_doorbell release (at least 0.8.7)

### ISSUE THREAD

**Issue by lastfreeusernameicouldfind** [fhempy/fhempy#427]
Hi all,
I would like to use my ring intercom device with fhempy. fhempy is currently using ring_doorbell 0.8.5. support of ring intercom is available from 0.8.7 onwards.
Would it be possible to use latest ring_doorbell?
Thanks and best regards

**Comment by fhempy** [comment]
Hi,
I accepted your PR but I'm not sure if the APIs remained unchanged in the ring package.
Please test and let me know if it works.

**Comment by lastfreeusernameicouldfind** [comment]
thanks!
I tried and tested it today but I am not able to confirm if its really working as it never worked before with my intercom as it was not yet supported in earlier releases. 
I can confirm that with the new release its able to find and connect to my intercom. But I am not getting any notifications/status updates in fhem when somebody rings. I am also not able to set any actions like open the door or ...

How should it work under normal conditions?

**Comment by reiphi** [comment]
Sorry for opening it up again. Is it planned to have a newer version of ring_doorbell within fhempy? Or is it possible to update the libs individually?

**Comment by jfmennedy** [comment]
Hi..

You need to update the version number in manifest.json in the ring doorbell folder and restart fhempy after, so the update will be installed automatically...

Greetings Jan

**Comment by reiphi** [comment]
Thank you, @jfmennedy. It works perfectly.

**Comment by jfmennedy** [comment]
👍 Just remind you need to modify again the version number if you do an update of fhempy while the latest version is not implemented in latest release of fhempy 😉 have a nice weekend...

**Comment by fhempy** [comment]
Please let me know which version works. If API changes are not required, I would update the manifest.
Thx!

**Comment by reiphi** [comment]
I successfully tested 0.9.9 which works with my Ring Intercom. I can't comment on all other Ring devices.
