### ISSUE TITLE
Repository markieren, damit es für das Docker Image berücksichtigt wird

### ISSUE THREAD

**Issue by sidey79** [fhempy/fhempy#439]
Das FHEM Dockerimage hat kein Protocol::WebSocket Modul, da es bisher kein anderes Modul benötigt.

Der build Prozess des Docker Images sucht auch GitHub Repos nach Bedarfen ab.

https://github.com/fhem/fhem-docker/blob/dev/scripts/get-FHEMRepositorys.sh

In diesem Repo liegen FHEM Module aber es ist kein language Tag für die Sprache Perl hinterlegt.
Daher wird dieses Repo nicht gefunden.

Wenn dieses Repo bei dieser Abfrage auftauchen würde, dann wäre das Modul im Image vorhanden:
https://github.com/topics/fhem?l=perl

**Comment by fhempy** [comment]
Hi,
weißt du wo ich den Language Tag setzen kann? Ich konnte dazu nur die Info finden, dass GitHub das automatisch macht und es nicht änderbar ist.

**Comment by sidey79** [comment]
Ja es geht über .gut Attributes

https://stackoverflow.com/questions/3305147/github-language-tag-for-repository

Allerdings kann es wohl nur ein einziges Tag für ein Repo geben :( das war mir nicht bewusst.
Kannst Du erst mal Perl und FHEM bei den Topics setzen? Vielleicht baue ich dann darauf eine Suche.

**Comment by fhempy** [comment]
Ich habe es mal bei den Topics hinzugefügt, lass mich wissen ob das so funktioniert. Danke!
