### ISSUE TITLE
Googlecast Verbesserungsvorschläge

### ISSUE THREAD

**Issue by saulous** [fhempy/fhempy#57]
Hello Dominik,

Vorab :
ich finde es großartig was du hier alles ablieferst und zusatzmodule für FHEM raus bringst.
Zur Zeit benutze ich den Tuya-cloud-connector und den Googlecast.

Da ich Zuhause mehrere Nest Audios mit einander in einer Gruppe habe würde ich diese gerne mit dem Googlecast Modul speisen.
Leider kann ich kein YouTube Link in den Gruppen abspielen. Einzeln klappt es. Vielleicht kann man dieses noch fixen ?

Wie wäre es evtl auch die Gruppen mit einer YouTube Playlist zu speisen ?
Und eventuell noch eine Shuffle funktion für die Playlists.

Danke Dir und weiter so  =)

**Comment by dominikkarall** [comment]
Hi,

was passiert wenn du versuchst einen YT Link an die Gruppe zu senden? Eigentlich ist die Gruppe aus fhempy Sicht genau das gleiche wie ein einzelnes Device.

**Comment by saulous** [comment]
hallo,

ich nutze die Befehlszeile (wie auch beim einzelnen Device) :
set castGruppe play url=youtubelink

Es passiert nach der eingabe garnichts. 
Bei einem einzelnen Device aktualisieren sich die Readings und die Wiedergabe startet nach kurzer Zeit.

Es wird keine Fehlermeldung im Log und im fhempy Log ausgegeben.
