### ISSUE TITLE
cryptography installation fails

### ISSUE THREAD

**Issue by kleinerDrache** [fhempy/fhempy#85]
hey ich bins mal wieder *gg* nachdem das alte problem für mich gelöst war lief eigentlich alles pefekt mit FHEMPY. Allerdings hab ich seit ein paar Tagen ständig "timeout" Meldungen im log und es geht garnix mehr...... weder lassen sich meine Steckdosen schalten noch kann ich Daten auslesen. Ich hänge eine FHEM.log und eine FHEMPY.log mit frisch aufgesetztem Lokalem Device an ;-) 

Schalten per APP funktioniert allerdings fehlerfrei

In der Fhem.txt steht nur der relevante teil drinn, sollte die vollständige datei gebraucht werden einfach melden.
Die FhemPY.txt ist gekürzt, der Fehler wiederholt sich ständig und die Datei erreicht in 5 min 10MB

[fhem-2022-08.log](https://github.com/fhempy/fhempy/files/9374151/fhem-2022-08.log)
[fhempy-2022-08-18.log](https://github.com/fhempy/fhempy/files/9374154/fhempy-2022-08-18.log)

**Comment by fhempy** [comment]
Hi,
bitte mit Version 0.1.424 testen, du hast noch 0.1.369.

**Comment by kleinerDrache** [comment]
hm wie bekomme ich das denn ? per Fhem update bleibt es bei der 0.1.369
auch der update button im FHEM-Py Device ändert nichts

Am Do., 18. Aug. 2022 um 16:47 Uhr schrieb Dominik ***@***.***

**Comment by kleinerDrache** [comment]
so nochmal ich ..... 

auch der Release direkt von hier geladen, und die Dateien im FHEM austauschen bringt nix,es bleibt bei der Version 0.1.369. Ein klicken auf update im device ändert nichts, fhem update vermeldet weiterhin "alles auf dem neuesten stand"

**Comment by fhempy** [comment]
sudo -U fhem bash
pip3 install --upgrade fhempy

**Comment by kleinerDrache** [comment]
hmmmmm erstes commando schlägt fehl mit der meldung das -U nicht alleine stehen darf.....
und das zweite dann mit einem buildfehler für wheel.

system hier ist ein Ubuntu 22.04.1 LTS ARM, fhem läuf aber unter dem user fhem

**Comment by fhempy** [comment]
Ach, sorry. Kleines u nicht großes.
sudo -u fhem bash
pip3 install --upgrade fhempy

**Comment by kleinerDrache** [comment]
komme zwar weiter aber der build schlägt immer noch fehl:

tim@jarvis:~$ sudo -u fhem bash
fhem@jarvis:/home/tim$ pip3 install --upgrade fhempy
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: fhempy in /opt/fhem/.local/lib/python3.10/site-packages (0.1.369)
Collecting fhempy
  Using cached fhempy-0.1.424-py3-none-any.whl (4.7 MB)
Collecting aiohttp[speedups]==3.8.1
  Using cached aiohttp-3.8.1.tar.gz (7.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: requests==2.26.0 in /opt/fhem/.local/lib/python3.10/site-packages (from fhempy) (2.26.0)
Requirement already satisfied: markdown2==2.4.2 in /opt/fhem/.local/lib/python3.10/site-packages (from fhempy) (2.4.2)
Requirement already satisfied: zeroconf==0.36.12 in /opt/fhem/.local/lib/python3.10/site-packages (from fhempy) (0.36.12)
Collecting cryptography==37.0.4
  Using cached cryptography-37.0.4.tar.gz (585 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]

              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:

              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================

      Traceback (most recent call last):
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-_riwx6ts/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-_riwx6ts/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
fhem@jarvis:/home/tim$

**Comment by fhempy** [comment]
Ist Python 10 Standard oder hast du es manuell installiert?

**Comment by kleinerDrache** [comment]
ist alles aus den Packetquellen installiert, hab mitlerweile mal die relevanten packete nachgeschaut, sind eigentlich alle schon von haus aus installiert als packete aus apt.

**Comment by fhempy** [comment]
Mach noch ein
pip3 install setuptools

**Comment by kleinerDrache** [comment]
fhem@jarvis:/home/tim$ pip3 list | grep setuptools
setuptools            65.1.0

sind wie gesagt schon installiert und genau wie pip selber auf der neuesten version

**Comment by fhempy** [comment]
Das hier wundert mich
ModuleNotFoundError: No module named 'setuptools.command.build'
  [end of output]

**Comment by kleinerDrache** [comment]
wunderte mich auch schon , hab versucht die crypto lib mal einzeln zu installieren. wird mir als satisfied angezeigt, kann es sein das da was mit dem pythonpath bei mir was nicht stimmt ?

**Comment by fhempy** [comment]
Hier findet man bisschen was dazu
https://github.com/openwrt/packages/issues/18876

**Comment by kleinerDrache** [comment]
ok scheint also an der Crypto lib zu liegen ...... was anderes hätte mich auch gewundert, aiohttp z.B läuft ja fehlerfrei durch und findet auch die Setuptools.

**Comment by fhempy** [comment]
Hier was bei setuptools
https://github.com/pypa/setuptools/discussions/3370

Eventuell eine ältere setuptools Version installieren?

**Comment by kleinerDrache** [comment]
was ich nicht ganz verstehe ist das die crypto ja da ist ....... aber im systempfad von python.

python3 -m pip install cryptography
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (3.4.8)

**Comment by fhempy** [comment]
3.4.8 ist aber zu alt. 37.0.4 sollte es glaube ich sein

**Comment by kleinerDrache** [comment]
ist halt die version die mit der ubuntu version hier kommt, deinstallieren mag ich die nicht wirklich da geht dann einiges wichtiges zeuch mit flöten.

**Comment by fhempy** [comment]
Ja ne, deinstallieren musst die eh nicht. Die ist systemweit installiert, fhempy inkl. Abhängigkeiten wird nur für den User fhem installiert.
Schon mal versucht eine ältere setuptools Version zu nutzen?

**Comment by kleinerDrache** [comment]
bisher nicht .... mach ich morgen mittag, geh jetzt ins bettchen um 5 geht der Wecker. Ich melde mich morgen nochmal ok ?

**Comment by fhempy** [comment]
Oder versuch noch das vorher
https://github.com/pypa/setuptools/discussions/3370#discussioncomment-2994764

**Comment by fhempy** [comment]
> bisher nicht .... mach ich morgen mittag, geh jetzt ins bettchen um 5 geht der Wecker. Ich melde mich morgen nochmal ok ?

👍

**Comment by kleinerDrache** [comment]
so bin jetzt bis zu version 62.4.0 der setuptools zurück gegangen ...... ändert nix, auch RUST hab ich neu gemacht inklusive der speziellen setuptools-rust, ändert alles nix. Selbst auf python 3.9 zurück zu gehen ändert nix.

**Comment by fhempy** [comment]
Pip Upgrade hilft auch nicht?

**Comment by kleinerDrache** [comment]
nope auch bei pip bin ich mitlerweile ein paar versionen durch gegangen

**Comment by fhempy** [comment]
Kommt immer der gleiche Fehler?

**Comment by fhempy** [comment]
was passiert wenn du
```
pip install --upgrade setuptools-rust
```
machst?

**Comment by kleinerDrache** [comment]
jup ist immer der gleiche Fehler (nicht gefundene setuptools) , und auch die setuptools-rust sind die aktuellsten.

**Comment by fhempy** [comment]
Probier bitte auch ein
```
pip3 install --upgrade wheel
```

Ich habe gerade Ubuntu 22.04 als Test in den Github Actions eingerichtet. Dort funktioniert die Installation.

**Comment by kleinerDrache** [comment]
Wheel lässt sich problemfrei aktualisieren ..... komischerweise läuft die installation von z.B. AIOHTTP ja durch (nutzt auch wheel) NUR Cryptography lässt sich in keiner höheren Version installieren als die schon im System vorhandene.

**Comment by fhempy** [comment]
Mach mal
pip3 uninstall setuptools-rust
pip3 install --upgrade cryptography
Poste mir dann bitte nochmals das Log

**Comment by fhempy** [comment]
> Hier findet man bisschen was dazu [openwrt/packages#18876](https://github.com/openwrt/packages/issues/18876)

Wie oben geschrieben, liegt das gleiche Problem bei openwrt vor. Siehe Link.

**Comment by kleinerDrache** [comment]
fhem@jarvis:/home/tim$ **pip3 uninstall setuptools-rust**
Found existing installation: setuptools-rust 1.5.1
Uninstalling setuptools-rust-1.5.1:
  Would remove:
    /opt/fhem/.local/lib/python3.10/site-packages/setuptools_rust-1.5.1.dist-info/*
    /opt/fhem/.local/lib/python3.10/site-packages/setuptools_rust/*
Proceed (Y/n)? y
  Successfully uninstalled setuptools-rust-1.5.1


fhem@jarvis:/home/tim$ **pip3 install --upgrade cryptography**
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: cryptography in /usr/lib/python3/dist-packages (3.4.8)
Collecting cryptography
  Using cached cryptography-37.0.4.tar.gz (585 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]

              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:

              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================

      Traceback (most recent call last):
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/fhem/.local/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-nj8m9u8s/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-nj8m9u8s/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

jup hatte den link gelesen , aber Englisch ist halt nicht meine Stärke

**Comment by fhempy** [comment]
Probier noch ein
```
sudo pip3 uninstall wheel
sudo -u fhem bash
pip3 uninstall wheel
pip3 install --upgrade cryptography
```

**Comment by kleinerDrache** [comment]
sorry das ich mich erst so spät melde......

wheel lässt sich nicht deinstallieren, ist eine per apt installierte Version. Deinstalliere ich das packet wird PIP gleich mit deinstalliert, installiere ich das neu wird das Wheel auch wieder installiert.

**Comment by ahermann86** [comment]
Ich habe nun deinen Vorschlag ausprobiert. Das sieht nun in der Bash so aus:

root@orangepione:~# apt-get install python3-setuptools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-setuptools is already the newest version (59.6.0-1.2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**Comment by fhempy** [comment]
Mach jetzt bitte ein
sudo -u fhem bash
pip3 install --upgrade fhempy

**Comment by ahermann86** [comment]
Das Ergebnis ist das:

9 KB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  Ã— Getting requirements to build wheel did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [29 lines of output]

              =============================DEBUG ASSISTANCE==========================
              If you are seeing an error here please try the following to
              successfully install cryptography:

              Upgrade to the latest pip and try again. This will fix errors for most
              users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
              =============================DEBUG ASSISTANCE==========================

      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/lib/python3/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "/usr/lib/python3/dist-packages/setuptools/build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 14, in <module>
          from setuptools_rust import RustExtension
        File "/tmp/pip-build-env-2vtdv1u6/overlay/local/lib/python3.10/dist-packages/setuptools_rust/__init__.py", line 1, in <module>
          from .build import build_rust
        File "/tmp/pip-build-env-2vtdv1u6/overlay/local/lib/python3.10/dist-packages/setuptools_rust/build.py", line 23, in <module>
          from setuptools.command.build import build as CommandBuild  # type: ignore[import]
      ModuleNotFoundError: No module named 'setuptools.command.build'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— Getting requirements to build wheel did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.


Würde es helfen, wenn ich dir meinen SSH Zugang freischalten würde?

**Comment by fhempy** [comment]
Ja, das wäre super. Kannst du mir das im fhem Forum (User dominik) schicken?

**Comment by fhempy** [comment]
Ich habe nun ein Issue direkt bei cryptography erstellt, da ich die Installation leider auch nicht hinbekommen habe:
https://github.com/pyca/cryptography/issues/7636

Mal sehen was dort an Rückmeldung dazu kommt.

**Comment by sidey79** [comment]
Ist das Problem noch akttuelle? Falls ihr noch daran hängt, ich habe mich für den dockerContainer jetzt durchgewurschtelt.

Nach etlichem frickeln klappt jetzt auch cryptography für ARM. 
Eines der Probleme war im "cargo" Paket weil ein git Abhängigkeit nicht aufgelöst werden kann.

**Comment by kleinerDrache** [comment]
ja ist noch aktuell ...... nutze zwar keinen Container aber ich bekomme crypto einfach nicht zum laufen. könntest Du Deine lösung etwas genauer beschreiben ?

**Comment by sidey79** [comment]
cmake muss installiert sein und für cargo braucht es noch eine Umgebungsvariable, da das sonst nicht geklappt hat:

`CARGO_NET_GIT_FETCH_WITH_CLI=true`

Wenn Du auf den Streß keine Lust hast, lässt Du fhem und fhempy in einem docker container laufen ;)
Ich habe zwar für fhempy noch nicht alle Module gebaut, bin aber guter Dinge dass das mittlerweile funktionieren würde.

**Comment by kleinerDrache** [comment]
werd mir das wohl antun müssen ;-) ich krieg aus dem Docker heraus keinen zugriff auf meine USB Geräte ...... trotzdem danke das du Deine erfahrungen weiter gibst

**Comment by sidey79** [comment]
@kleinerDrache 

USB Geräte gehen auch durchgereicht in einem Docker Container, einfach das Gerät durchreichen.
Vorausgesetzt, der HOST läuft nicht unter Windows und Du versucht über WSL dann noch Docker zu betreiben, da scheitet es aber eher daran, dass das WSL kein Zugriff auf die USB Geräte durch den Hypervisor bekommt.

**Comment by kleinerDrache** [comment]
nene ist Linux auf nem Cubietruck, das durchreichen klappt nicht weil ich mehrere Dienste habe die auf dem Host laufen (HM-USB Stick mit hmland, der Stick für die Zigbee Geräte) und die Dienste blocken das USB schon auf dem Host, entweder laufen diese Dienste oder ich kann USB durchreichen. Mischbetrieb hab bisher nicht ans laufen bekommen.

**Comment by sidey79** [comment]
Das kannst Du ja je Gerät individuelle einstellen.
Darf ich fragen, welches USB Gerät für fhempy von Interesse wäre?

**Comment by kleinerDrache** [comment]
bisher nur das Zigbee Zeuch ;-) nutze damit ein paar tuya Steckdosen.

**Comment by kleinerDrache** [comment]
zigbee läuft über Zigbee2Mqtt

**Comment by fhempy** [comment]
> Ist das Problem noch akttuelle? Falls ihr noch daran hängt, ich habe mich für den dockerContainer jetzt durchgewurschtelt.
> 
> Nach etlichem frickeln klappt jetzt auch cryptography für ARM. Eines der Probleme war im "cargo" Paket weil ein git Abhängigkeit nicht aufgelöst werden kann.

Hier dürfte eine Lösung gefunden worden sein:
https://github.com/pyca/cryptography/issues/7636#issuecomment-1282401889

Tritt das Problem aktuell noch bei jemanden auf?

**Comment by ahermann86** [comment]
Danke wür den Hinweis - Ich habe es gerade ausprobiert.
Es funktioniert nun auch für meinen Orange Pi One mit "Armbian 22.08.8 Jammy with Linux 5.15.74-sunxi"

**Comment by kleinerDrache** [comment]
bin bisher noch nicht dazu gekommen das aus zu probieren, melde mich aber bald mit Erfolg oder Misserfolg ;-)

**Comment by fhempy** [comment]
Super, danke euch für die Rückmeldung!

Ich lass das hier noch offen, damit andere es auch schnell finden.

**Hier die Lösung für das Problem:**
https://github.com/pyca/cryptography/issues/7636#issuecomment-1282401889

**Comment by fhempy** [comment]
Ich habe nun cryptography durch pycryptodome ersetzt. Diese Library sollte bei der Installation weniger Probleme machen.

Issue wird daher geschlossen. Sollte jemand mit pycryptodome Probleme haben, bitte ein neues Issue aufmachen.

**Comment by sidey79** [comment]
@fhempy 

Hast Du das auch bei allen "Modulen" ersetzen können? Da hing es bei dem docker image zuletzt. Glaube bei den Modulen für seat und co.
