### ISSUE TITLE
Tuya Devices (local) wont come online 

### ISSUE THREAD

**Issue by jfmennedy** [fhempy/fhempy#87]
In the latest version (451) tuya devices wont come online :

Sep 05 14:57:24 pi fhempy[33377]: 2022-09-05 14:57:24,500 - ERROR    - smKonvektor: Failed create_device
Sep 05 14:57:24 pi fhempy[33377]: Traceback (most recent call last):
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 412, in create_device
Sep 05 14:57:24 pi fhempy[33377]:     await self._create_mapping_dev()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 127, in _create_mapping_dev
Sep 05 14:57:24 pi fhempy[33377]:     await self._generate_set()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 178, in _generate_set
Sep 05 14:57:24 pi fhempy[33377]:     options = list(values["translation"].values())
Sep 05 14:57:24 pi fhempy[33377]: KeyError: 'translation'
Sep 05 14:57:24 pi fhempy[33377]: 2022-09-05 14:57:24,597 - ERROR    - flKonvektor: Failed create_device
Sep 05 14:57:24 pi fhempy[33377]: Traceback (most recent call last):
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 412, in create_device
Sep 05 14:57:24 pi fhempy[33377]:     await self._create_mapping_dev()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 127, in _create_mapping_dev
Sep 05 14:57:24 pi fhempy[33377]:     await self._generate_set()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 178, in _generate_set
Sep 05 14:57:24 pi fhempy[33377]:     options = list(values["translation"].values())
Sep 05 14:57:24 pi fhempy[33377]: KeyError: 'translation'
Sep 05 14:57:24 pi fhempy[33377]: 2022-09-05 14:57:24,647 - ERROR    - sm_Heizkonvektor: Failed create_device
Sep 05 14:57:24 pi fhempy[33377]: Traceback (most recent call last):
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 412, in create_device
Sep 05 14:57:24 pi fhempy[33377]:     await self._create_mapping_dev()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 127, in _create_mapping_dev
Sep 05 14:57:24 pi fhempy[33377]:     await self._generate_set()
Sep 05 14:57:24 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 178, in _generate_set
Sep 05 14:57:24 pi fhempy[33377]:     options = list(values["translation"].values())
Sep 05 14:57:24 pi fhempy[33377]: KeyError: 'translation'
Sep 05 14:57:25 pi fhempy[33377]: 2022-09-05 14:57:25,880 - ERROR    - wzKonvektor: Failed create_device
Sep 05 14:57:25 pi fhempy[33377]: Traceback (most recent call last):
Sep 05 14:57:25 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 412, in create_device
Sep 05 14:57:25 pi fhempy[33377]:     await self._create_mapping_dev()
Sep 05 14:57:25 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 127, in _create_mapping_dev
Sep 05 14:57:25 pi fhempy[33377]:     await self._generate_set()
Sep 05 14:57:25 pi fhempy[33377]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 178, in _generate_set
Sep 05 14:57:25 pi fhempy[33377]:     options = list(values["translation"].values())
Sep 05 14:57:25 pi fhempy[33377]: KeyError: 'translation'

**Comment by fhempy** [comment]
Thanks for reporting! Can you please test 0.1.453, that one should fix the bug.

**Comment by jfmennedy** [comment]
Updated to 455 and issue is fixed
