### ISSUE TITLE
Tuya Fensterkontakte

### ISSUE THREAD

**Issue by avdreith** [fhempy/fhempy#89]
Hallo, ich habe diese Fensterkontakte gekauft: https://www.amazon.de/gp/product/B09L7K99WY/ref=ppx_yo_dt_b_asin_title_o02_s00?ie=UTF8&psc=1

Die Fensterkontakte werden in FHEM angezeigt. Das Problem ist, dass nur der Status für online/offline aktualisiert wird. Der Status on oder off wird nur sporadisch aktualisiert. Woran kann das liegen? In der Tuya-App wird der Status immer aktualisiert. Aber in FHEM kommt das nicht an. 

defmod test_contact fhempy tuya py9zrqqb4qgjwynh bf3cc1406363a475c6us0o 192.168.177.143 e5e7c5fdf6f190a8 3.3 rau5du5mbknw5ohl5x5u 7ba3451d36314a96a8081d4e08972ee7
attr test_contact dp_01 doorcontact_state
attr test_contact dp_02 battery_percentage
attr test_contact group tuya
attr test_contact room fhempy
attr test_contact tuya_spec_functions []
attr test_contact tuya_spec_status [{'code': 'doorcontact_state', 'dp_id': 1, 'type': 'Boolean', 'values': '{}'}, {'code': 'battery_percentage', 'dp_id': 2, 'type': 'Integer', 'values': '{"unit":"%","min":0,"max":100,"scale":0,"step":1}'}]

setstate test_contact offline
setstate test_contact 2022-09-05 17:25:17 active_time 1662151681
setstate test_contact 2022-09-05 17:26:47 battery_percentage 100.0
setstate test_contact 2022-09-05 17:25:17 biz_type 0
setstate test_contact 2022-09-05 17:25:17 category mcs
setstate test_contact 2022-09-05 17:25:17 create_time 1662151681
setstate test_contact 2022-09-06 18:55:55 doorcontact_state off
setstate test_contact 2022-09-05 17:23:42 dp_01 0
setstate test_contact 2022-09-05 17:23:42 dp_02 100
setstate test_contact 2022-09-05 17:25:17 icon smart/icon/ay1572620709242ZjWXS/cf9f05b81314dc7589eb00cc1c3dceb1.png
setstate test_contact 2022-09-05 17:25:17 id bf3cc1406363a475c6us0o
setstate test_contact 2022-09-05 17:25:17 ip 91.96.142.168
setstate test_contact 2022-09-05 17:25:17 lat 53.8221
setstate test_contact 2022-09-05 17:25:17 local_key e5e7c5fdf6f190a8
setstate test_contact 2022-09-05 17:25:17 lon 9.2921
setstate test_contact 2022-09-05 17:25:17 model WIFI-MC-092
setstate test_contact 2022-09-05 17:25:17 name Contact Sensor 2
setstate test_contact 2022-09-05 17:25:17 online 1
setstate test_contact 2022-09-05 17:25:17 owner_id 27774330
setstate test_contact 2022-09-05 17:25:17 product_id py9zrqqb4qgjwynh
setstate test_contact 2022-09-05 17:25:17 product_name Contact Sensor
setstate test_contact 2022-09-08 19:04:54 state offline
setstate test_contact 2022-09-05 17:25:17 sub 0
setstate test_contact 2022-09-05 17:25:17 time_zone +02:00
setstate test_contact 2022-09-05 17:25:17 uid eu1616150391098UfjXd
setstate test_contact 2022-09-05 17:25:17 update_time 1662151685
setstate test_contact 2022-09-05 17:25:17 uuid 231d14ad3a1126cc

Gruß
Andreas

**Comment by Spieke96** [comment]
Hey ich musste mich mit dem selben Problem auseinander setzen.

Wenn eine Alexa im Haus vorhanden ist es stabil lösbar indem man sein FHEM mit Alexa connected, dummy’s anlegt für die Fensterkontakte und dann eine Routine erstellt die sagt wenn Tuya Fensterkontakte An dann schalte FHEM dummy an bzw andersrum.

Das ist zwar etwas umständlich läuft dafür sehr stabil.

Vielleicht ist das eine Alternative.

Viele Grüße
