### ISSUE TITLE
gosund SP112_RTL device doesn't show energy reading

### ISSUE THREAD

**Issue by pseudex** [fhempy/fhempy#90]
### Model
Name | value
-- | --
model | SP112_RTL 
name | Smart Socket
product_id | zmql6aexy8ua5rox
product_name | Smart Socket

dp_id | name | deleteattr
-- | -- | --
dp_01 | switch_1 | deleteattr
dp_07 | switch_usb1 | deleteattr
dp_09 | countdown_1 | deleteattr
dp_15 | countdown_usb1 | deleteattr
dp_18 | cur_current | deleteattr
dp_19 | cur_power | deleteattr
dp_20 | cur_voltage | deleteattr
dp_38 | relay_status | deleteattr
dp_39 | light_mode | deleteattr
dp_40 | child_lock | deleteattr
dp_41 | cycle_time | deleteattr
dp_42 | random_time | deleteattr

`[{'code': 'switch_1', 'dp_id': 1, 'type': 'Boolean', 'values': '{}'}, {'code': 'switch_usb1', 'dp_id': 7, 'type': 'Boolean', 'values': '{}'}, {'code': 'countdown_1', 'dp_id': 9, 'type': 'Integer', 'values': '{"unit":"s","min":0,"max":86400,"scale":0,"step":1}'}, {'code': 'countdown_usb1', 'dp_id': 15, 'type': 'Integer', 'values': '{"unit":"s","min":0,"max":86400,"scale":0,"step":1}'}, {'code': 'add_ele', 'dp_id': 17, 'type': 'Integer', 'values': '{"unit":"kwh","min":0,"max":50000,"scale":3,"step":100}'}, {'code': 'cur_current', 'dp_id': 18, 'type': 'Integer', 'values': '{"unit":"mA","min":0,"max":30000,"scale":0,"step":1}'}, {'code': 'cur_power', 'dp_id': 19, 'type': 'Integer', 'values': '{"unit":"W","min":0,"max":50000,"scale":1,"step":1}'}, {'code': 'cur_voltage', 'dp_id': 20, 'type': 'Integer', 'values': '{"unit":"V","min":0,"max":5000,"scale":1,"step":1}'}, {'code': 'relay_status', 'dp_id': 38, 'type': 'Enum', 'values': '{"range":["power_off","power_on","last"]}'}, {'code': 'light_mode', 'dp_id': 39, 'type': 'Enum', 'values': '{"range":["none","relay","pos"]}'}, {'code': 'child_lock', 'dp_id': 40, 'type': 'Boolean', 'values': '{}'}, {'code': 'cycle_time', 'dp_id': 41, 'type': 'String', 'values': '{}'}, {'code': 'random_time', 'dp_id': 42, 'type': 'String', 'values': '{}'}]`

I try to figure out why dp_17 is not shown
`{'code': 'add_ele', 'dp_id': 17, 'type': 'Integer', 'values': '{"unit":"kwh","min":0,"max":50000,"scale":3,"step":100}'}`

if I try to add it myself it wouldn't let me
`[Smart_Socket_bfc] unknown attribute dp_17. Type 'attr [Smart_Socket_bfc] Smart_Socket_bfc) ?' for a detailed list.`

this will output
`unknown attribute ?, choose one of alias comment eventMap group room suppressReading userattr userReadings verbose tuya_spec_functions tuya_spec_status dp_01 dp_07 dp_09 dp_15 dp_18 dp_19 dp_20 dp_21 dp_22 dp_23 dp_24 dp_25 dp_38 dp_39 dp_40 dp_41 dp_42 dp_43 dp_101 IODev href='/fhem?detail=fhempy_local'>fhempy_local event-aggregator event-min-interval event-on-change-reading event-on-update-reading oldreadings stateFormat timestamp-on-change-reading DbLogExclude DbLogInclude DbLogValueFn cmdIcon devStateIcon devStateIcon devStateStyle icon sortby webCmd webCmdLabel widgetOverride `

so far I had no luck finding the reason in code. I also cannot find the product_id | zmql6aexy8ua5rox in the mappings.py.
does the dp_17 have to be added manually in the python code or should it come from the tuya_spec_status?

**Comment by fhempy** [comment]
It seems that dp_17 wasn't discovered on the device. Please try the following:
 - disconnect plug from power
 - connect plug to power
 - restart fhempy
 - check if dp_17 attribute was found

If that doesn't work try to reset the device and repeat the procedure above.

If it still doesn't work, I'll check what I can do to allow unknown DP ids.

**Comment by pseudex** [comment]
thank you. the socket was fresh from the box. now I connected a load and the energy counter is 0.01kWh on the app.
I deleted the socket from fhem and let it create again. Now the reading shows up.
Before I tried the same thing. This time the only difference is the counter > 0.

Are the readings available also fetched from the device and checked with the mappings.py?

**Comment by fhempy** [comment]
It depends how the device was created. I assume you used API KEY/SECRET. In this case the attributes are fetched from TuYa cloud. Mappings.py is only used when cloud API is not on use - API parameters not specified in define. I recommend to use those as not all devices are covered in the mappings.py.

**Comment by fhempy** [comment]
To be a little more specific:
- attributes are fetched from TuYa cloud
- Device is discovered locally including the DP IDs.
- the IDs are afterwards matched with the attributes to have a proper naming for the readings

**Comment by pseudex** [comment]
ahh. this is why my product id is not in the mappings.py. I created the socket from the tuya_system. This is setup with the api key/secret.

thank you for the clarification.
I almost sent the sockets back because they are not flashable with tasmota anymore. Now they should be perfect to use.
