### ISSUE TITLE
fhempy crashes repeatedly

### ISSUE THREAD

**Issue by jfmennedy** [fhempy/fhempy#93]
Hi Dominik,

my fhempy instance running on a remote peer crashes repeatedly which leads in huge delays of my fhem instance when restarting.
In the last days even fhem restarted several times with following log entry before the restart:

fhem-log:
Too many fragments at /usr/local/share/perl/5.28.1/Protocol/WebSocket/Frame.pm line 232

fhempy-log:
Sep 12 04:38:49 pi fhempy[4092]: 2022-09-12 04:38:49,197 - ERROR    - fhempy.lib.fhem: Timeout - NO RESPONSE for command: readingsBulkUpdateIfChanged($defs{'Google_Cast_Group_Erdgeschoss_ohne_WZ'},'display_name>
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,897 - ERROR    - fhempy.lib.fhem_pythonbinding: Connection closed error
Sep 12 04:38:50 pi fhempy[4092]: Traceback (most recent call last):
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
Sep 12 04:38:50 pi fhempy[4092]:     message = await self.read_message()
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
Sep 12 04:38:50 pi fhempy[4092]:     frame = await self.read_data_frame(max_size=self.max_size)
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
Sep 12 04:38:50 pi fhempy[4092]:     frame = await self.read_frame(max_size)
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
Sep 12 04:38:50 pi fhempy[4092]:     frame = await Frame.read(
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 70, in read
Sep 12 04:38:50 pi fhempy[4092]:     data = await reader(2)
Sep 12 04:38:50 pi fhempy[4092]:   File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
Sep 12 04:38:50 pi fhempy[4092]:     raise exceptions.IncompleteReadError(incomplete, n)
Sep 12 04:38:50 pi fhempy[4092]: asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 2 expected bytes
Sep 12 04:38:50 pi fhempy[4092]: The above exception was the direct cause of the following exception:
Sep 12 04:38:50 pi fhempy[4092]: Traceback (most recent call last):
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 78, in pybinding
Sep 12 04:38:50 pi fhempy[4092]:     async for message in websocket:
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
Sep 12 04:38:50 pi fhempy[4092]:     yield await self.recv()
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
Sep 12 04:38:50 pi fhempy[4092]:     await self.ensure_open()
Sep 12 04:38:50 pi fhempy[4092]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 921, in ensure_open
Sep 12 04:38:50 pi fhempy[4092]:     raise self.connection_closed_exc()
Sep 12 04:38:50 pi fhempy[4092]: websockets.exceptions.ConnectionClosedError: no close frame received or sent
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,899 - INFO     - fhempy.lib.fhem_pythonbinding: Restart fhempy
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,904 - INFO     - websockets.server: server closing
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,915 - INFO     - websockets.server: connection closed
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,920 - INFO     - websockets.server: server closed
Sep 12 04:38:50 pi fhempy[4092]: 2022-09-12 04:38:50,926 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
Sep 12 04:38:52 pi fhempy[6026]: 2022-09-12 04:38:52,529 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.461...
Sep 12 04:38:52 pi fhempy[6026]: 2022-09-12 04:38:52,542 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
Sep 12 04:38:52 pi fhempy[6026]: 2022-09-12 04:38:52,931 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Sep 12 04:38:53 pi fhempy[6026]: 2022-09-12 04:38:53,004 - INFO     - websockets.server: server listening on 0.0.0.0:15733
Sep 12 04:41:11 pi fhempy[6026]: 2022-09-12 04:41:11,723 - INFO     - websockets.server: connection open
Sep 12 04:41:11 pi fhempy[6026]: 2022-09-12 04:41:11,730 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249
Sep 12 04:41:14 pi fhempy[6026]: 2022-09-12 04:41:14,912 - WARNING  - asyncio: Executing <Task pending name='Task-20' coro=<WebSocketServerProtocol.handler() running at /home/pi/.local/lib/python3.9/site-packag>
Sep 12 04:41:26 pi fhempy[6026]: 2022-09-12 04:41:26,949 - ERROR    - fhempy.lib.core.discover_fhempy.discover_fhempy: async_get_service_info failed for _http._tcp.local. - .

**Comment by fhempy** [comment]
There seem to be 2 issues:
 - websocket connection gets unstable due to high traffic. Based on the fhem.log message it's due to too many fragments. I'm not sure if I can limit fragments in the python websockets implementation. Can you please check if disabling events (comment out line 236 in 10_BindingsIo.pm) helps?
 - async_get_service_info failed for _http._tcp.local. - .
Looks like some strange service on your network. The service name is just ".". You can check the service names on your network with the ServiceBrowser app on Android for example.

**Comment by jfmennedy** [comment]
Are you sure its line 236? If I uncomment on reload i get errors where $hash is used:
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_BindingsIo.pm line 237.
Global symbol "$hash" requires explicit package name (did you forget to declare "my $hash"?) at ./FHEM/10_BindingsIo.pm line 239.

Need to wait to come home to check the service...

**Comment by jfmennedy** [comment]
I switched to local binding and local it did not crash once since 6 hours.. My network is very duty (about 150 clients), perhaps too many collisions...

**Comment by jfmennedy** [comment]
So my peer is running now without any device attached to it and it restarts sometimes with this log:

Sep 14 20:34:38 pi fhempy[1625]: 2022-09-14 20:34:38,699 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249
Sep 15 07:13:00 pi fhempy[1625]: 2022-09-15 07:13:00,403 - INFO     - websockets.server: connection open
Sep 15 07:13:00 pi fhempy[1625]: 2022-09-15 07:13:00,404 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249
Sep 15 07:13:10 pi fhempy[1625]: 2022-09-15 07:13:10,250 - ERROR    - fhempy.lib.fhem_pythonbinding: Connection closed error
Sep 15 07:13:10 pi fhempy[1625]: Traceback (most recent call last):
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 80, in read
Sep 15 07:13:10 pi fhempy[1625]:     opcode = frames.Opcode(head1 & 0b00001111)
Sep 15 07:13:10 pi fhempy[1625]:   File "/usr/lib/python3.9/enum.py", line 360, in __call__
Sep 15 07:13:10 pi fhempy[1625]:     return cls.__new__(cls, value)
Sep 15 07:13:10 pi fhempy[1625]:   File "/usr/lib/python3.9/enum.py", line 677, in __new__
Sep 15 07:13:10 pi fhempy[1625]:     raise ve_exc
Sep 15 07:13:10 pi fhempy[1625]: ValueError: 6 is not a valid Opcode
Sep 15 07:13:10 pi fhempy[1625]: The above exception was the direct cause of the following exception:
Sep 15 07:13:10 pi fhempy[1625]: Traceback (most recent call last):
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
Sep 15 07:13:10 pi fhempy[1625]:     message = await self.read_message()
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
Sep 15 07:13:10 pi fhempy[1625]:     frame = await self.read_data_frame(max_size=self.max_size)
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
Sep 15 07:13:10 pi fhempy[1625]:     frame = await self.read_frame(max_size)
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
Sep 15 07:13:10 pi fhempy[1625]:     frame = await Frame.read(
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 82, in read
Sep 15 07:13:10 pi fhempy[1625]:     raise ProtocolError("invalid opcode") from exc
Sep 15 07:13:10 pi fhempy[1625]: websockets.exceptions.ProtocolError: invalid opcode
Sep 15 07:13:10 pi fhempy[1625]: The above exception was the direct cause of the following exception:
Sep 15 07:13:10 pi fhempy[1625]: Traceback (most recent call last):
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 78, in pybinding
Sep 15 07:13:10 pi fhempy[1625]:     async for message in websocket:
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
Sep 15 07:13:10 pi fhempy[1625]:     yield await self.recv()
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
Sep 15 07:13:10 pi fhempy[1625]:     await self.ensure_open()
Sep 15 07:13:10 pi fhempy[1625]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
Sep 15 07:13:10 pi fhempy[1625]:     raise self.connection_closed_exc()
Sep 15 07:13:10 pi fhempy[1625]: websockets.exceptions.ConnectionClosedError: sent 1002 (protocol error); no close frame received
Sep 15 07:13:10 pi fhempy[1625]: 2022-09-15 07:13:10,251 - INFO     - fhempy.lib.fhem_pythonbinding: Restart fhempy
Sep 15 07:13:10 pi fhempy[1625]: 2022-09-15 07:13:10,252 - INFO     - websockets.server: server closing
Sep 15 07:13:10 pi fhempy[1625]: 2022-09-15 07:13:10,256 - INFO     - websockets.server: connection closed
Sep 15 07:13:20 pi fhempy[1625]: 2022-09-15 07:13:20,265 - INFO     - websockets.server: connection closed
Sep 15 07:13:20 pi fhempy[1625]: 2022-09-15 07:13:20,266 - INFO     - websockets.server: connection closed
Sep 15 07:13:20 pi fhempy[1625]: 2022-09-15 07:13:20,266 - INFO     - websockets.server: server closed
Sep 15 07:13:20 pi fhempy[1625]: 2022-09-15 07:13:20,268 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,116 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.462...
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,119 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,487 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,518 - INFO     - websockets.server: server listening on 0.0.0.0:15733
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,540 - INFO     - websockets.server: connection open
Sep 15 07:13:21 pi fhempy[2133]: 2022-09-15 07:13:21,541 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.2
Sep 15 07:13:30 pi fhempy[2133]: 2022-09-15 07:13:30,294 - INFO     - websockets.server: connection open
Sep 15 07:13:30 pi fhempy[2133]: 2022-09-15 07:13:30,295 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249
Sep 15 07:17:03 pi fhempy[2133]: 2022-09-15 07:17:03,053 - ERROR    - fhempy.lib.fhem_pythonbinding: Connection closed error
Sep 15 07:17:03 pi fhempy[2133]: Traceback (most recent call last):
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 80, in read
Sep 15 07:17:03 pi fhempy[2133]:     opcode = frames.Opcode(head1 & 0b00001111)
Sep 15 07:17:03 pi fhempy[2133]:   File "/usr/lib/python3.9/enum.py", line 360, in __call__
Sep 15 07:17:03 pi fhempy[2133]:     return cls.__new__(cls, value)
Sep 15 07:17:03 pi fhempy[2133]:   File "/usr/lib/python3.9/enum.py", line 677, in __new__
Sep 15 07:17:03 pi fhempy[2133]:     raise ve_exc
Sep 15 07:17:03 pi fhempy[2133]: ValueError: 14 is not a valid Opcode
Sep 15 07:17:03 pi fhempy[2133]: The above exception was the direct cause of the following exception:
Sep 15 07:17:03 pi fhempy[2133]: Traceback (most recent call last):
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 945, in transfer_data
Sep 15 07:17:03 pi fhempy[2133]:     message = await self.read_message()
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1015, in read_message
Sep 15 07:17:03 pi fhempy[2133]:     frame = await self.read_data_frame(max_size=self.max_size)
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1090, in read_data_frame
Sep 15 07:17:03 pi fhempy[2133]:     frame = await self.read_frame(max_size)
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 1145, in read_frame
Sep 15 07:17:03 pi fhempy[2133]:     frame = await Frame.read(
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/framing.py", line 82, in read
Sep 15 07:17:03 pi fhempy[2133]:     raise ProtocolError("invalid opcode") from exc
Sep 15 07:17:03 pi fhempy[2133]: websockets.exceptions.ProtocolError: invalid opcode
Sep 15 07:17:03 pi fhempy[2133]: The above exception was the direct cause of the following exception:
Sep 15 07:17:03 pi fhempy[2133]: Traceback (most recent call last):
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py", line 78, in pybinding
Sep 15 07:17:03 pi fhempy[2133]:     async for message in websocket:
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 482, in __aiter__
Sep 15 07:17:03 pi fhempy[2133]:     yield await self.recv()
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 553, in recv
Sep 15 07:17:03 pi fhempy[2133]:     await self.ensure_open()
Sep 15 07:17:03 pi fhempy[2133]:   File "/home/pi/.local/lib/python3.9/site-packages/websockets/legacy/protocol.py", line 930, in ensure_open
Sep 15 07:17:03 pi fhempy[2133]:     raise self.connection_closed_exc()
Sep 15 07:17:03 pi fhempy[2133]: websockets.exceptions.ConnectionClosedError: sent 1002 (protocol error); no close frame received
Sep 15 07:17:03 pi fhempy[2133]: 2022-09-15 07:17:03,054 - INFO     - fhempy.lib.fhem_pythonbinding: Restart fhempy
Sep 15 07:17:03 pi fhempy[2133]: 2022-09-15 07:17:03,055 - INFO     - websockets.server: server closing
Sep 15 07:17:03 pi fhempy[2133]: 2022-09-15 07:17:03,058 - INFO     - websockets.server: connection closed
Sep 15 07:17:13 pi fhempy[2133]: 2022-09-15 07:17:13,067 - INFO     - websockets.server: connection closed
Sep 15 07:17:13 pi fhempy[2133]: 2022-09-15 07:17:13,067 - INFO     - websockets.server: server closed
Sep 15 07:17:13 pi fhempy[2133]: 2022-09-15 07:17:13,069 - INFO     - fhempy.lib.fhem_pythonbinding: Exit 1
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,097 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.462...
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,101 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,471 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,502 - INFO     - websockets.server: server listening on 0.0.0.0:15733
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,526 - INFO     - websockets.server: connection open
Sep 15 07:17:14 pi fhempy[2142]: 2022-09-15 07:17:14,527 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.2
Sep 15 07:17:23 pi fhempy[2142]: 2022-09-15 07:17:23,920 - INFO     - websockets.server: connection open
Sep 15 07:17:23 pi fhempy[2142]: 2022-09-15 07:17:23,920 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249

**Comment by jfmennedy** [comment]
My latest observations :

I got only one googlecast connected to the peer. When I start streaming, the peer begins to restart and I have delays in fhem ..

Might it be possible that the event handling causes the issue? When casting many events are created (media Current Position, mediaCurrentPosPercent)..

If so, is it possible to create an attribute to enable /disable the event handling?

**Comment by fhempy** [comment]
Sorry, I had BindingsIo already modified, therefore the line number was incorrect.

Exactly, what I want to check if the error depends on the number of events. Can you please comment out line 212:
```
#BindingsIo_Write($hash, $dev, "event", [$event], {});
```

That disables the events.

**Comment by jfmennedy** [comment]
I uncommented that line already earlier last week after my last comment and the system is running stable since than. no crash of fhempy for the whole time...

**Comment by fhempy** [comment]
I think this one can be closed now? Due to the fix in version 0.1.475.
