### ISSUE TITLE
Tuya - Pool-Heat-Pump - Betriebsmodi fehlt

### ISSUE THREAD

**Issue by olgo59** [fhempy/fhempy#97]
Hallo,
ich nutz das fhempy Tool für verschiedene Dinge - Tuya und Meross aktuell.
Aktueller Stand: 0.1.473

Leider wird mir bei mein Poolheizung nicht der aktive Modus angezeigt und daher kann ich diesen auch nicht via fhem ändern.
Im Log finde ich leider nichts. 
Ich kann über die App"Smart Life" folgende Dinge ändern:
- Ein/Aus
- Soll-Temperatur
- Modus (Silent Heat, ECO Heat, Boost Heat, Auto und ECO Cool)

In der Tuya IoT Plattform kann ich in den Deice Logs folgendes sehen:

Time                          | Device Event | DP ID  | Event Details | Source | Source Details

2022-09-23 11:58:06 | Report           | Mode | ECO Heat       | device itself

Leider sehe ich diese Daten nicht in fhem bei meinem Device.

Was kann ich machen um den Modus auch über fhem steuern zu können.

Vielen Dank

defmod Pool_Heat_Pump_37666602ecfabcd87531 PythonModule tuya_cloud tuya_cloud_connector 37666602ecfabcd87531
attr Pool_Heat_Pump_37666602ecfabcd87531 alias Pool Heat Pump
attr Pool_Heat_Pump_37666602ecfabcd87531 group tuya_cloud
attr Pool_Heat_Pump_37666602ecfabcd87531 room fhempy

setstate Pool_Heat_Pump_37666602ecfabcd87531 on
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 active_time 1654093993
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 biz_type 18
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 category qn
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 create_time 1629991366
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 icon https://images.tuyaeu.com/smart/icon/ay1546932630554g7i66/3706fbe29466eda8236289f0741c2f1b.png
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 id 37666602ecfabcd87531
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 ip 93.245.179.153
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 lat 51.5882
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 local_key 11e7019c7dc41ef0
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 lon 7.7438
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 model Pool-Amitime
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 name Pool Heat Pump
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 online on
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 owner_id 57795399
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 product_id 3bhylhz5zhogklel
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 product_name Pool Heat Pump
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 11:58:22 state on
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 sub off
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 11:58:22 temp_current 12.0
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 11:58:22 temp_set 28.0
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 time_zone +01:00
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 uid eu1653507323402tuXyL
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 update_time 1662378579
setstate Pool_Heat_Pump_37666602ecfabcd87531 2022-09-23 09:12:12 uuid 37666602ecfabcd87531

**Comment by fhempy** [comment]
Hi,
ich gehe davon aus, dass der Modus ein nicht nach Tuya Standards konformer Typ ist. Daher wird es über die Cloud nicht steuern gehen.
Probier tuya (statt tuya_cloud) aus, damit sollte es machbar sein. Es gibt dann ein dp_ Reading welches wahrscheinlich der Mode ist.

Btw, bevor du das Device anlegst, lösche vorher das aktuelle, da es sonst wegen gleichen Namen nicht angelegt wird.

**Comment by olgo59** [comment]
Hallo,
das habe ich bereits gemacht, hier sehe ich auch die dp_Register, aber leider keinen Modus.

attr Pool_Heat_Pump_37666602ecfabcd87531 alias Pool Heat Pump
attr Pool_Heat_Pump_37666602ecfabcd87531 dp_01 switch
attr Pool_Heat_Pump_37666602ecfabcd87531 dp_02 temp_set
attr Pool_Heat_Pump_37666602ecfabcd87531 dp_03 temp_current
attr Pool_Heat_Pump_37666602ecfabcd87531 group tuya
attr Pool_Heat_Pump_37666602ecfabcd87531 room fhempy
attr Pool_Heat_Pump_37666602ecfabcd87531 tuya_spec_functions [{'code': 'switch', 'dp_id': 1, 'type': 'Boolean', 'values': '{}', 'desc': 'switch'}, {'code': 'temp_set', 'dp_id': 2, 'type': 'Integer', 'values': '{"unit":"°C","min":0,"max":40,"scale":0,"step":1}', 'desc': 'temp set'}]
attr Pool_Heat_Pump_37666602ecfabcd87531 tuya_spec_status [{'code': 'switch', 'dp_id': 1, 'type': 'Boolean', 'values': '{}'}, {'code': 'temp_set', 'dp_id': 2, 'type': 'Integer', 'values': '{"unit":"°C","min":0,"max":40,"scale":0,"step":1}'}, {'code': 'temp_current', 'dp_id': 3, 'type': 'Integer', 'values': '{"unit":"°C","min":-20,"max":50,"scale":0,"step":1}'}]


Somit gibt Tuya dieses Register nicct aus und ich kann es nicht vuia fhem steuern, richtig?

Vielen Dank

**Comment by fhempy** [comment]
Welche Readings werden angezeigt? Änder sich ein Reading beim Modus Ändern?

**Comment by olgo59** [comment]
Hallo Dominik,Es ist der dp4Der wird bei der local Installation auch angezeigt😀Also funktioniert es im Gegensatz zur Cloud VersionPerfektVielen Dank Von meinem iPhone gesendetAm 23.09.2022 um 15:53 schrieb Dominik ***@***.***>:﻿
Welche Readings werden angezeigt? Änder sich ein Reading beim Modus Ändern?
